force-app/main/default/objects/PaymentType__c/PaymentType__c.object-meta.xml
<CustomObject>
    <label>Payment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTypeDetail__c/PaymentTypeDetail__c.object-meta.xml
<CustomObject>
    <label>Payment Type Detail</label>
    <nameField>
        <label>Payment Type Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Type Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTypeDetail__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <referenceTo>PaymentType__c</referenceTo>
    <relationshipLabel>Payment Type Details</relationshipLabel>
    <relationshipName>PaymentTypeDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreatePaymentTypeDetailController.cls
/**
 * @description       : 
 * @author            : ¤ → alessio.marra@nexusat.it
 * @last modified on  : 03/01/2023
 * @last modified by  : ¤ → alessio.marra@nexusat.it
**/
public class CreatePaymentTypeDetailController {
	
	@AuraEnabled
	public static Integer getMaxRankPaymentType(String paymentTypeId) {
		System.debug('¤ paymentTypeId: ' + paymentTypeId);
		
		AggregateResult[] aggrs = [
				SELECT PaymentType__c
						,MAX(Rank__c) max
				FROM PaymentTypeDetail__c
				WHERE PaymentType__c = :paymentTypeId
				GROUP BY PaymentType__c];
		if (aggrs.isEmpty()) {
			return 0;
		} else {
			return Integer.valueOf(aggrs[0].get('max'));
		}
	}
}