force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntranetAPI__c/IntranetAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Intranet API</label>
</CustomObject>

force-app/main/default/objects/IntranetAPI__c/fields/BaseUrl__c.field-meta.xml
<CustomField>
    <fullName>BaseUrl__c</fullName>
    <label>BaseUrl</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntranetAPI__c/fields/PreviewDocumentEndpoint__c.field-meta.xml
<CustomField>
    <fullName>PreviewDocumentEndpoint__c</fullName>
    <label>Preview Document</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PdfPreviewControllerTest.cls
/**
 * @description       : 
 * @author            : ¤ → alessio.marra@nexusat.it
 * @last modified on  : 16/12/2022
 * @last modified by  : ¤ → alessio.marra@nexusat.it
**/
@isTest
private class PdfPreviewControllerTest {

    @testSetup
    static void makeData() {
        IntranetAPI__c intranetAPI = new IntranetAPI__c(
            BaseUrl__c = 'baseUrl',
            Username__c = 'username',
            Password__c = 'password',
            PreviewDocumentEndpoint__c = 'previewDocument'
        );
        insert intranetAPI;

        DocumentAlyante__c document = new DocumentAlyante__c(
            ExtIdAlyante__c = 'extid'
        );
        insert document;
    }

    @isTest
    private static void testGetCredentials() {
        // Test data setup
        IntranetAPI__c intranetAPI = IntranetAPI__c.getOrgDefaults();

        // Actual test
        Test.startTest();
        IntranetAPI__c credentials = PdfPreviewController.getCredentials();
        Test.stopTest();

        // Asserts
        System.assertEquals(intranetAPI, credentials);
    }

    @isTest
    private static void testGetDocumentRecord() {
        // Test data setup
        Id documentId = [SELECT Id FROM DocumentAlyante__c LIMIT 1].Id;

        // Actual test
        Test.startTest();
        DocumentAlyante__c document = PdfPreviewController.getDocumentRecord(documentId);
        Test.stopTest();

        // Asserts
        System.assertEquals(documentId, document.Id);
    }

    
    @isTest
    private static void testGetDocumentRecordWrongId() {
        // Test data setup
        String documentId = 'wrongid';

        // Actual test
        Test.startTest();
        try {
            DocumentAlyante__c document = PdfPreviewController.getDocumentRecord(documentId);
            System.assert(false);
        } catch (Exception e) {
            System.assert(true);
        }
        Test.stopTest();
    }
}