force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ProjectStatus__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/recordTypes/Bulk.recordType-meta.xml
<RecordType>
    <fullName>Bulk</fullName>
    <active>true</active>
    <label>Bulk</label>
</RecordType>

force-app/main/default/objects/DocumentDetailAlyante__c/recordTypes/Final.recordType-meta.xml
<RecordType>
    <fullName>Final</fullName>
    <active>true</active>
    <label>Final</label>
</RecordType>

force-app/main/default/objects/OpportunityDocumentAlyante__c/OpportunityDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Opportunity - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity - Documents Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/ProjectStatus__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectStatus__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/createDocumentDetailAlyanteController.cls
/**
 * @description       : 
 * @author            : mattia.miglietta@nexusat.it
 * @last modified on  : 27/01/2023
 * @last modified by  : ¤ → alessio.marra@nexusat.it
**/
public with sharing class createDocumentDetailAlyanteController {
    @AuraEnabled(cacheable=true)
    public static Map<String, String> getRecordDefaultValues(String documentRecordId){
        Map<String, String> fieldValues = new Map<String, String>();
        try {
            List <OpportunityDocumentAlyante__c> oppDocuments = [SELECT Id, Opportunity__c FROM OpportunityDocumentAlyante__c WHERE DocumentAlyante__c = :documentRecordId];
            if(oppDocuments.size() > 0) {
                ProjectStatus__c proj = [SELECT Id FROM ProjectStatus__c WHERE Opportunity__c = :oppDocuments[0].Opportunity__c LIMIT 1];
                fieldValues.put('Project__c', proj.Id);
            }
            return fieldValues;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Id> getRecordTypesAvailable() {
        List<RecordType> recordTypesAvailable = [
            SELECT Id FROM RecordType
            WHERE SobjectType = 'DocumentDetailAlyante__c'
            AND IsActive = true
            AND DeveloperName IN ('Bulk', 'Final')
        ];
        return new List<Id>((new Map<Id,RecordType>(recordTypesAvailable)).keySet());
    }
}