force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/EndCompetence__c.field-meta.xml
<CustomField>
    <fullName>EndCompetence__c</fullName>
    <label>End Competence</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ProjectStatus__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/RevenueType__c.field-meta.xml
<CustomField>
    <fullName>RevenueType__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/StartCompetence__c.field-meta.xml
<CustomField>
    <fullName>StartCompetence__c</fullName>
    <label>Start Competence</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sviluppo software</fullName>
            </value>
            <value>
                <fullName>Manutenzione correttiva</fullName>
            </value>
            <value>
                <fullName>Manutenzione adeguativa</fullName>
            </value>
            <value>
                <fullName>Manutenzione evolutiva</fullName>
            </value>
            <value>
                <fullName>Manutenzione normativa</fullName>
            </value>
            <value>
                <fullName>Manutenzione migliorativa</fullName>
            </value>
            <value>
                <fullName>Formazione</fullName>
            </value>
            <value>
                <fullName>Assistenza onsite - help desk I° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza onsite - help desk II° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza remota - help desk I° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza remota - help desk II° livello</fullName>
            </value>
            <value>
                <fullName>Governance</fullName>
            </value>
            <value>
                <fullName>Conduzione</fullName>
            </value>
            <value>
                <fullName>Hosting e housing infrastruttura</fullName>
            </value>
            <value>
                <fullName>Conservazione sostitutiva</fullName>
            </value>
            <value>
                <fullName>Gestione processi interni</fullName>
            </value>
            <value>
                <fullName>Sistema atti, protocollo</fullName>
            </value>
            <value>
                <fullName>Sistema documentale</fullName>
            </value>
            <value>
                <fullName>Sistema Gestione qualità</fullName>
            </value>
            <value>
                <fullName>Sistema e-procurement</fullName>
            </value>
            <value>
                <fullName>Portali e applicativi web</fullName>
            </value>
            <value>
                <fullName>Mobile application</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Applicazioni con IOT</fullName>
            </value>
            <value>
                <fullName>Applicazioni con AI</fullName>
            </value>
            <value>
                <fullName>Fornitura hardware/strumenti IT</fullName>
            </value>
            <value>
                <fullName>Supporto specialistico/consulenziale</fullName>
            </value>
            <value>
                <fullName>Ambito sanità</fullName>
            </value>
            <value>
                <fullName>Ambito turismo</fullName>
            </value>
            <value>
                <fullName>Ambito e-government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/InvoiceMilestoneDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Milestone - Document Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Invoice Milestone - Document Alyante</relationshipLabel>
    <relationshipName>InvoiceMilestoneDocumentAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/fields/InvoiceMilestone__c.field-meta.xml
<CustomField>
    <fullName>InvoiceMilestone__c</fullName>
    <label>Invoice Milestone</label>
    <referenceTo>InvoiceMilestone__c</referenceTo>
    <relationshipLabel>Invoice Milestone - Document Alyante</relationshipLabel>
    <relationshipName>InvoiceMilestoneDocumentAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/OpportunityDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Opportunity - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity - Documents Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/ProjectStatus__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectStatus__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloneDraftInvoiceController.cls
/**
 * @description       : 
 * @author            : §
 * @group             : 
 * @last modified on  : 01-31-2022
 * @last modified by  : §
**/
public class CloneDraftInvoiceController {
    
    @AuraEnabled(cacheable=true)
    public static List<Id> fetchOpportunityId(Id recordId){
        
        List<OpportunityDocumentAlyante__c> oppDocIdList = [SELECT Opportunity__c FROM OpportunityDocumentAlyante__c WHERE DocumentAlyante__c = :recordId];
        Set<Id> ids = new Set<Id>();
        for(OpportunityDocumentAlyante__c v : oppDocIdList){
            ids.add(v.Opportunity__c);
        }
        return new List<Id>(ids);
    }  
    
    @AuraEnabled(cacheable=true)
    public static List<Id> fetchInvoiceMilestoneId(Id recordId){
        
        List<InvoiceMilestoneDocumentAlyante__c> invoiceMilestoneIdList = [SELECT InvoiceMilestone__c FROM InvoiceMilestoneDocumentAlyante__c WHERE DocumentAlyante__c = :recordId];
        Set<Id> ids = new Set<Id>();
        for(InvoiceMilestoneDocumentAlyante__c v : invoiceMilestoneIdList){
            ids.add(v.InvoiceMilestone__c);
        }
        return new List<Id>(ids);
    }

    @AuraEnabled
    public static void cloneDocumentDetails(Id recordId, Id clonedDocumentId){
        List<DocumentDetailAlyante__c> documentDetails = new List<DocumentDetailAlyante__c>();

        documentDetails = [SELECT Amount__c, Content__c, Document__c, EndCompetence__c, Project__c, RevenueType__c, StartCompetence__c, Tags__c
                           FROM DocumentDetailAlyante__c
                           WHERE Document__c = :recordId];

        List<DocumentDetailAlyante__c> clonedList = documentDetails.deepClone(false, false, false);

        for(DocumentDetailAlyante__c clone : clonedList) {
            clone.Document__c = clonedDocumentId;
        }

         try {
            insert clonedList;    
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<DocumentDetailAlyante__c> getDocumentDetails(Id recordId){
        List<DocumentDetailAlyante__c> documentDetails = new List<DocumentDetailAlyante__c>();
        try {
            documentDetails = [SELECT Amount__c, Name, Content__c, Document__c, EndCompetence__c, Project__c, Project__r.Name, RevenueType__c, StartCompetence__c, Tags__c
                            FROM DocumentDetailAlyante__c
                            WHERE Document__c = :recordId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return documentDetails;
    }    
    @AuraEnabled
    public static List<DocumentDetailAlyante__c> createDocumentDetails(List<DocumentDetailAlyante__c> documentDetails) {
        try {
            insert documentDetails;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return documentDetails;
    }
    @AuraEnabled
    public static void deleteDocument(Id docId){
        DocumentAlyante__c doc = new DocumentAlyante__c(Id = docId);
        try {
            delete doc;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}