force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentAlyante__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/EndCompetence__c.field-meta.xml
<CustomField>
    <fullName>EndCompetence__c</fullName>
    <label>End Competence</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>ProjectStatus__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/RevenueType__c.field-meta.xml
<CustomField>
    <fullName>RevenueType__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/StartCompetence__c.field-meta.xml
<CustomField>
    <fullName>StartCompetence__c</fullName>
    <label>Start Competence</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sviluppo software</fullName>
            </value>
            <value>
                <fullName>Manutenzione correttiva</fullName>
            </value>
            <value>
                <fullName>Manutenzione adeguativa</fullName>
            </value>
            <value>
                <fullName>Manutenzione evolutiva</fullName>
            </value>
            <value>
                <fullName>Manutenzione normativa</fullName>
            </value>
            <value>
                <fullName>Manutenzione migliorativa</fullName>
            </value>
            <value>
                <fullName>Formazione</fullName>
            </value>
            <value>
                <fullName>Assistenza onsite - help desk I° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza onsite - help desk II° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza remota - help desk I° livello</fullName>
            </value>
            <value>
                <fullName>Assistenza remota - help desk II° livello</fullName>
            </value>
            <value>
                <fullName>Governance</fullName>
            </value>
            <value>
                <fullName>Conduzione</fullName>
            </value>
            <value>
                <fullName>Hosting e housing infrastruttura</fullName>
            </value>
            <value>
                <fullName>Conservazione sostitutiva</fullName>
            </value>
            <value>
                <fullName>Gestione processi interni</fullName>
            </value>
            <value>
                <fullName>Sistema atti, protocollo</fullName>
            </value>
            <value>
                <fullName>Sistema documentale</fullName>
            </value>
            <value>
                <fullName>Sistema Gestione qualità</fullName>
            </value>
            <value>
                <fullName>Sistema e-procurement</fullName>
            </value>
            <value>
                <fullName>Portali e applicativi web</fullName>
            </value>
            <value>
                <fullName>Mobile application</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Applicazioni con IOT</fullName>
            </value>
            <value>
                <fullName>Applicazioni con AI</fullName>
            </value>
            <value>
                <fullName>Fornitura hardware/strumenti IT</fullName>
            </value>
            <value>
                <fullName>Supporto specialistico/consulenziale</fullName>
            </value>
            <value>
                <fullName>Ambito sanità</fullName>
            </value>
            <value>
                <fullName>Ambito turismo</fullName>
            </value>
            <value>
                <fullName>Ambito e-government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/StartSendEmailWorkflow__c.field-meta.xml
<CustomField>
    <fullName>StartSendEmailWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SendEmail Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>Invoice Year</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/InvoiceMilestoneDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Milestone - Document Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Invoice Milestone - Document Alyante</relationshipLabel>
    <relationshipName>InvoiceMilestoneDocumentAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneDocumentAlyante__c/fields/InvoiceMilestone__c.field-meta.xml
<CustomField>
    <fullName>InvoiceMilestone__c</fullName>
    <label>Invoice Milestone</label>
    <referenceTo>InvoiceMilestone__c</referenceTo>
    <relationshipLabel>Invoice Milestone - Document Alyante</relationshipLabel>
    <relationshipName>InvoiceMilestoneDocumentAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/OpportunityDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Opportunity - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity - Documents Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/ProjectStatus__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectStatus__c/fields/BudgetDD__c.field-meta.xml
<CustomField>
    <fullName>BudgetDD__c</fullName>
    <label>Budget (dd)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/EmailNotification__c.field-meta.xml
<CustomField>
    <fullName>EmailNotification__c</fullName>
    <defaultValue>&apos;stefano.bellante@nexusat.it&apos;</defaultValue>
    <label>EmailNotification</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>ReferenceNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analisi requisiti</fullName>
                <default>true</default>
                <label>Analisi requisiti</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>WIP</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Deploy in Produzione</fullName>
            </value>
            <value>
                <fullName>Supporto post go-live</fullName>
            </value>
            <value>
                <fullName>Completato</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
                <isActive>false</isActive>
                <label>Fatturato</label>
            </value>
            <value>
                <fullName>Invio Fattura</fullName>
                <isActive>false</isActive>
                <label>Invio Fattura</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloneDraftInvoiceControllerTest.cls
@isTest
public class CloneDraftInvoiceControllerTest {
    
    @TestSetup static void makeData(){
        
        Account acc = new Account();
        acc.Name = 'Acc Name';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Opp Name';
        opp.CloseDate = Date.Today().addDays(10);
        opp.StageName = 'Prospeting';
        insert opp;
        
        ProjectStatus__c ps = new ProjectStatus__c(
            Name = 'Status',
            //RecordTypeId = '01209000000l0oLAAQ',
            Opportunity__c = opp.Id,
            Account__c = acc.Id,
            BudgetDD__c = 2.0,
            EmailNotification__c = 'roberto.desimone@nexusat.it',
            ReferenceNumber__c = 'LK-00000',
            SendInvoiceEmail__c = false,
            Stage__c = 'Analisi requisiti',
            UpdateDate__c = Date.newInstance(2022,02,01));
      	insert ps;
        
        DocumentAlyante__c da = new DocumentAlyante__c();
        da.Date__c = Date.today();
        insert da;
        
        DocumentDetailAlyante__c dda = new DocumentDetailAlyante__c();
        dda.Amount__c = 30;
        dda.Content__c = 'Test Content';
        dda.Document__c = da.Id;
        dda.EndCompetence__c = Date.Today().addDays(10);
        dda.Project__c = ps.Id;
        dda.RevenueType__c = '25';
        dda.StartCompetence__c = Date.Today();
        dda.Tags__c = 'Sviluppo software;Manutenzione correttiva';
        insert dda;
        
            
        OpportunityDocumentAlyante__c oppDA = new OpportunityDocumentAlyante__c();
        oppDa.Opportunity__c = opp.Id;
        oppDa.DocumentAlyante__c = da.Id;
        insert oppDa;
        
        InvoiceMilestone__c im = new InvoiceMilestone__c(
            Name = 'LK-00000 - Tes - 90',
            RecordTypeId = '01209000000mArWAAU',
            //Amount__c = 20000.0,
            //Description__c = '40 - Test',
            ExpectedDate__c = Date.newInstance(2022,01,12),
            //Rank__c = 1.0,
            Stage__c = 'Draft',
            StartSendEmailWorkflow__c = false,
            Opportunity__c = opp.Id,
            Year__c = '2022');
        insert im;
        
        InvoiceMilestoneDocumentAlyante__c imDA = new InvoiceMilestoneDocumentAlyante__c();
        imDA.InvoiceMilestone__c = im.Id;
        imDA.DocumentAlyante__c = da.Id;
        insert imDA;
        
        
    }
    
    @isTest
    public static void fetchOpportunityIdTest(){
        Id daId = [SELECT Id FROM DocumentAlyante__c].Id;
        Test.startTest();
        CloneDraftInvoiceController.fetchOpportunityId(daId);
        Test.stopTest();
    }
    
    @isTest
    public static void fetchInvoiceMilestoneIdTest(){
        Id daId = [SELECT Id FROM DocumentAlyante__c].Id;
        Test.startTest();
        CloneDraftInvoiceController.fetchInvoiceMilestoneId(daId);
        Test.stopTest();
    }
    
    @isTest
    public static void cloneDocumentDetailsTest(){
        id ddaId = [SELECT Id FROM DocumentDetailAlyante__c].id;
        id daId = [SELECT Id FROM DocumentAlyante__c].id;
        Test.startTest();
		CloneDraftInvoiceController.cloneDocumentDetails(ddaId, daId);
		Test.stopTest();        
    }
}