force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityDocumentAlyante__c/OpportunityDocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Opportunity - Document Alyante</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity - Documents Alyante</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/DocumentAlyante__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyante__c</fullName>
    <label>Document Alyante</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityDocumentAlyante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity - Documents Alyante</relationshipLabel>
    <relationshipName>OpportunityDocumentsAlyante</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/ProjectStatus__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectStatus__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DocumentDetailControllerTest.cls
/**
 * @description       : 
 * @author            : mattia.miglietta@nexusat.it
 * @last modified on  : 15-11-2022
 * @last modified by  : mattia.miglietta@nexusat.it
**/
@isTest
public with sharing class DocumentDetailControllerTest {
    @TestSetup
    static void makeData(){
        DocumentAlyante__c doc = new DocumentAlyante__c();
        insert doc;
        Opportunity opp = new Opportunity(Name='test', StageName='test', CloseDate=System.today());
        insert opp;
        OpportunityDocumentAlyante__c oppAndDoc = new OpportunityDocumentAlyante__c(Opportunity__c=opp.Id, DocumentAlyante__c = doc.Id);
        insert oppAndDoc;
        ProjectStatus__c proj  = new ProjectStatus__c(Opportunity__c= opp.Id);
        insert proj;
    }
    @isTest
    static void getProjectTest() {
        DocumentAlyante__c doc = [SELECT Id FROM DocumentAlyante__c LIMIT 1];
        createDocumentDetailAlyanteController.getRecordDefaultValues(doc.Id);
    }
}