force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OnDocumentDetailAlyanteTriggerHelper.cls
public class OnDocumentDetailAlyanteTriggerHelper {
    
    public static List<DocumentDetailAlyante__c> blockCreateRecords(List<DocumentDetailAlyante__c> triggerNew) {
        
        if(isAdminUser()) {
            return new List<DocumentDetailAlyante__c>();
        }
        
        List<DocumentDetailAlyante__c> documentDetailsToBlock = new List<DocumentDetailAlyante__c>();
        Map<Id, List<DocumentDetailAlyante__c>> documentDetailsByDocument = new Map<Id, List<DocumentDetailAlyante__c>>();
        
        for (DocumentDetailAlyante__c documentDetail : triggerNew){
            List<DocumentDetailAlyante__c> details = new List<DocumentDetailAlyante__c>();
            if(documentDetailsByDocument.containsKey(documentDetail.Document__c)){
                details.addAll(documentDetailsByDocument.get(documentDetail.Document__c));
            }
            details.add(documentDetail);
            documentDetailsByDocument.put(documentDetail.Document__c, details);
        }
        
        for (Id documentId : documentDetailsByDocument.keySet()) {
            if(Approval.isLocked(documentId)){
                for(DocumentDetailAlyante__c documentDetail : documentDetailsByDocument.get(documentId)){
                    documentDetailsToBlock.add(documentDetail);
                }
            }
        }
        return documentDetailsToBlock;
    }
    
    private static Boolean isAdminUser() {
        return [SELECT PermissionsModifyAllData FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1].PermissionsModifyAllData;
    }
}