force-app/main/default/objects/Quote/fields/LinksTotalHRCost__c.field-meta.xml
<CustomField>
    <fullName>LinksTotalHRCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total HR Cost</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TotalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalCost__c</fullName>
    <formula>OvernightAllowanceCost__c +  TravelAllowanceCost__c +   DDTotalCost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemTriggerHelper.cls
/**
 * @description       : 
 * @author            : Œ
 * @group             : 
 * @last modified on  : 04-05-2021
 * @last modified by  : Œ
 * Modifications Log 
 * Ver   Date         Author   Modification
 * 1.0   03-25-2021   Œ   Initial Version
**/
public class QuoteLineItemTriggerHelper {
    

    public static void quoteLineItemUpdateTotalHRCost(List<QuoteLineItem> triggerQuoteLine) {
        System.debug('Œ QuoteLineItemTriggerHelper - quoteLineItemUpdateTotalHRCost'  );
        
       
       
      Set<Id> quoteIDLst = new Set<Id>(); 
        for (QuoteLineItem record : triggerQuoteLine){
            quoteIDLst.add(record.QuoteId);
        }
        System.debug('Œ quoteLineItemUpdateTotalHRCost  QUOTE ID LIST' + quoteIDLst);

        List<Quote> quoteList = [SELECT Id, LinksTotalHRCost__c, (SELECT id, TotalCost__c FROM QuoteLineItems)
                                 FROM Quote
                                 WHERE id =:quoteIDLst];

        List<Quote> updatedQuoteList = new List<Quote>();
       
        for (Quote quoteRecord : quoteList){
          
            quoteRecord.LinksTotalHRCost__c = 0;
            for (QuoteLineItem quoteLineItemRecord: quoteRecord.QuoteLineItems){
                    quoteRecord.LinksTotalHRCost__c +=   quoteLineItemRecord.TotalCost__c;               
            }
           Quote q = new Quote(
             id = quoteRecord.id,
             LinksTotalHRCost__c = quoteRecord.LinksTotalHRCost__c
           );
           updatedQuoteList.add(q);
        }

        update updatedQuoteList;
      
       
    }
}