force-app/main/default/objects/Invoice_Milestone__c/Invoice_Milestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Milestone__c/fields/Ammontare__c.field-meta.xml
<CustomField>
    <fullName>Ammontare__c</fullName>
    <label>Ammontare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Data_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_prevista__c</fullName>
    <label>Data prevista</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices Milestone</relationshipLabel>
    <relationshipName>Billing_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Stato__c.field-meta.xml
<CustomField>
    <fullName>Stato__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/recordTypes/Recursive.recordType-meta.xml
<RecordType>
    <fullName>Recursive</fullName>
    <active>true</active>
    <label>Recursive</label>
</RecordType>

force-app/main/default/classes/ProgressBarControllerTest.cls
@isTest
public class ProgressBarControllerTest {
    @TestSetup
    static void makeData(){
        //Insert Account
        Account testAccount = New Account(Name = 'testAccount');
        insert testAccount;
        //Insert Contact
        Contact testContactCustomer = new Contact(FirstName = 'Test', LastName = 'Test', AccountId = testAccount.Id);
        insert testContactCustomer;
        //Insert Opportunity -->Recursive
        Opportunity opp = New Opportunity();
        opp.Name = 'oppTest';
        opp.AccountId = testAccount.Id;
        opp.CloseDate = Date.today();
        opp.StageName = 'Prospecting';
        insert opp;
        //Get RecordType of Invoice_Milestone__c
        Id invMilRecTypId = [SELECT Id, DeveloperName FROM RecordType WHERE DeveloperName = 'Recursive'].Id;
         //Insert Invoice_Milestone__c
        Invoice_Milestone__c imTest = New Invoice_Milestone__c();
        imTest.Name = 'Invoice Milestone Test';
        imTest.Opportunity__c = opp.Id;
        imTest.Data_prevista__c = Date.today();
        imTest.RecordTypeId = invMilRecTypId;
        imTest.Ammontare__c = 1000;
        imTest.Stato__c = 'Fattura Inviata';
        insert imTest;
    }
    @isTest
    static void getOppFieldsTest(){
        Opportunity opp = [SELECT Id 
                    FROM Opportunity
                    LIMIT 1];
        Id oppId = opp.Id;
        ProgressBarController.getOppFields(oppId);
    }
}