force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project Status</label>
    <referenceTo>Project_Status__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worklog__c/Worklog__c.object-meta.xml
<CustomObject>
    <label>Worklog</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Worklog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worklogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worklog__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Worklogs</relationshipLabel>
    <relationshipName>Worklogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RicalcoloCosti.cls
global class RicalcoloCosti implements Database.Batchable<sObject> {
    private String oppId;
    
    global RicalcoloCosti(String oppId){
        this.oppId = oppId;
    }
    
    @AuraEnabled
    public static void updateCosti(Id recordId){
        system.debug('Ø-recordId ' + recordId);
        database.executebatch(new RicalcoloCosti(recordId));
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Id prjId = [SELECT Opportunity__c, Id FROM Project_Status__c WHERE Opportunity__c =: oppId].Id;
        return Database.getQueryLocator('SELECT Id, Name, Issue__c FROM Worklog__c WHERE Issue__r.Project__c =: prjId');
    }
    
    global void execute(Database.BatchableContext bc, List<Worklog__c> scope){
        update scope;
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    } 
}