force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/JiraId__c.field-meta.xml
<CustomField>
    <fullName>JiraId__c</fullName>
    <description>Jira Id</description>
    <externalId>true</externalId>
    <label>Jira Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project Status</label>
    <referenceTo>Project_Status__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunitySetting__c/OpportunitySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Opportunity Setting</label>
</CustomObject>

force-app/main/default/objects/OpportunitySetting__c/fields/FteWhere__c.field-meta.xml
<CustomField>
    <fullName>FteWhere__c</fullName>
    <label>FteWhere</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Budget_gg__c.field-meta.xml
<CustomField>
    <fullName>Budget_gg__c</fullName>
    <label>Budget (gg)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Data_fine_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_fine_prevista__c</fullName>
    <label>Data fine prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Stima_gg_a_terminare__c.field-meta.xml
<CustomField>
    <fullName>Stima_gg_a_terminare__c</fullName>
    <label>Stima a terminare (gg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Worklog__c/Worklog__c.object-meta.xml
<CustomObject>
    <label>Worklog</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Worklog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Worklogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Worklog__c/fields/IdTempo__c.field-meta.xml
<CustomField>
    <fullName>IdTempo__c</fullName>
    <externalId>true</externalId>
    <label>Id Tempo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Worklog__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <label>Issue</label>
    <referenceTo>Issue__c</referenceTo>
    <relationshipLabel>Worklogs</relationshipLabel>
    <relationshipName>Worklogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RicalcoloCostiTest.cls
/**
 * @description       : 
 * @author            : alessio.marra@nexusat.it ¤
 * @last modified on  : 22/01/2021
 * @last modified by  : alessio.marra@nexusat.it ¤
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   22/01/2021   alessio.marra@nexusat.it ¤   Initial Version
**/
@isTest
public class RicalcoloCostiTest {}

//     private static void insertCustomSettings() {
//         OpportunitySetting__c customSettings = new OpportunitySetting__c();
//         customSettings.FteWhere__c = 'Name = \'Project Test\'';
//         insert customSettings;
//     }
    
// 	private static Id insertAccount(String name) {
//         Account acc = new Account();
//         acc.Name = name;
//         insert acc;
//         return acc.Id;
//     }
    
//     private static Id insertOpportunity(String name, Id accId) {
//         Opportunity opp = new Opportunity();
//         opp.Name = name;
//         opp.accountId = accId;
//         opp.StageName = 'Prospect';
//         opp.CloseDate = Date.today();
//         insert opp;
//         return opp.Id;
//     }
    
//     private static Id insertProjectStatus(String name, Id oppId) {
//         Project_Status__c prj = new Project_Status__c();
//         prj.Name = name;
//         prj.Budget_gg__c = 10000;
//         prj.Data_fine_prevista__c = Date.today()+30;
//         prj.Stima_gg_a_terminare__c = 5;
//         prj.Opportunity__c = oppId;
//         insert prj;
//         return prj.Id;
//     }
        
//     private static Id insertIssue(String jiraId, Id prjId) {
//         Issue__c issue = new Issue__c();
//         issue.JiraId__c = jiraId;
//         issue.Project__c = prjId;
//         insert issue;
//         return issue.Id;
//     }
    
//     private static Id insertWorklog(String idTempo, Id issId) {
//         Worklog__c worklog = new Worklog__c();
//         worklog.IdTempo__c = idTempo;
//         worklog.Issue__c = issId;
//         insert worklog;
//         return worklog.Id;
//     }
    
//     @TestSetup
//     static void makeData(){
//         insertCustomSettings();
//         Id accId = insertAccount('Account Test');
//         Id oppId = insertOpportunity('Opportunity Test', accId);
//         Id prjId = insertProjectStatus('Project Test', oppId);
//         Id issId = insertIssue('JiraId Test', prjId);
//         insertWorklog('IdTempo Test', issId);
//     }
    
//     @isTest
//     static void updateCosti(){
//         Id oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
//         Test.StartTest();
//         RicalcoloCosti.updateCosti(oppId);
//         Test.StopTest();
//     }
// }