force-app/main/default/objects/Account/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DeliveryProjectManager__c.field-meta.xml
<CustomField>
    <fullName>DeliveryProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunitySetting__c/OpportunitySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Opportunity Setting</label>
</CustomObject>

force-app/main/default/objects/OpportunitySetting__c/fields/DefaultDeliveryManagerEmail__c.field-meta.xml
<CustomField>
    <fullName>DefaultDeliveryManagerEmail__c</fullName>
    <label>DefaultDeliveryManagerEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/OpportunitySetting__c/fields/FteWhere__c.field-meta.xml
<CustomField>
    <fullName>FteWhere__c</fullName>
    <label>FteWhere</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ProjectSetting__mdt/ProjectSetting__mdt.object-meta.xml
<CustomObject>
    <label>ProjectSetting</label>
    <pluralLabel>ProjectSetting</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProjectSetting__mdt/fields/UpdatableField__c.field-meta.xml
<CustomField>
    <fullName>UpdatableField__c</fullName>
    <label>UpdatableField</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/ProjectStatus__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectStatus__c/fields/AverageFTE__c.field-meta.xml
<CustomField>
    <fullName>AverageFTE__c</fullName>
    <label>Average FTE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/BudgetDD__c.field-meta.xml
<CustomField>
    <fullName>BudgetDD__c</fullName>
    <label>Budget (dd)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/EmailNotification__c.field-meta.xml
<CustomField>
    <fullName>EmailNotification__c</fullName>
    <defaultValue>&apos;stefano.bellante@nexusat.it&apos;</defaultValue>
    <label>EmailNotification</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/EstimatedToFinishDD__c.field-meta.xml
<CustomField>
    <fullName>EstimatedToFinishDD__c</fullName>
    <label>Estimated To Finish (dd)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/ExpectedEndDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedEndDate__c</fullName>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>ReferenceNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/RemainingFTE__c.field-meta.xml
<CustomField>
    <fullName>RemainingFTE__c</fullName>
    <label>Remaining FTE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analisi requisiti</fullName>
                <default>true</default>
                <label>Analisi requisiti</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>WIP</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Deploy in Produzione</fullName>
            </value>
            <value>
                <fullName>Supporto post go-live</fullName>
            </value>
            <value>
                <fullName>Completato</fullName>
            </value>
            <value>
                <fullName>Fatturato</fullName>
                <isActive>false</isActive>
                <label>Fatturato</label>
            </value>
            <value>
                <fullName>Invio Fattura</fullName>
                <isActive>false</isActive>
                <label>Invio Fattura</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progetto</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProjectStatus__c/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/classes/OnProjectStatusHelper.cls
/**
 * @description       : 
 * @author            : 
 * @last modified on  : 25/01/2021
 * @last modified by  : ¤ → alessio.marra@nexusat.it
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0                                               Initial Version
 * 1.1   25/01/2021   ¤ → alessio.marra@nexusat.it   Review ApiName Nomenclature
**/
global class OnProjectStatusHelper{
	
	public class customException extends exception{}
	
	private static String whereClausole = OpportunitySetting__c.getOrgDefaults().FteWhere__c;
	private static String changeFieldsCheck = [Select UpdatableField__c from ProjectSetting__mdt Limit 1].UpdatableField__c;
	private static String DefaultDeliveryManagerEmail = OpportunitySetting__c.getOrgDefaults().DefaultDeliveryManagerEmail__c;
	Map<Id,Opportunity> opportunityMap;
	public OnProjectStatusHelper(List<ProjectStatus__c> projectsStatus){
		Set<Id> OpportunitiesId = new Set<Id>();
		for(ProjectStatus__c projectStatus : projectsStatus){
			OpportunitiesId.add(projectStatus.Opportunity__c);
		}
		opportunityMap = new Map<Id,Opportunity>([SELECT Id,AccountId,ReferenceNumber__c,DeliveryProjectManager__c,DeliveryProjectManager__r.Email FROM Opportunity WHERE Id in: OpportunitiesId]);

	}
	private static String baseQuery = 'SELECT' 
										+' MAX(ExpectedEndDate__c) gratestDate'
										+',MIN(ExpectedEndDate__c) smallestDate'
										+',SUM(EstimatedToFinishDD__c) stimaAterminareTot'
										+',COUNT(Id) nRecord'
										+' FROM ProjectStatus__c'
										+' WHERE RecordType.DeveloperName = \'Nexus\' AND ';
	private static date 	gratestDate;
	private static date 	smallestDate;
	private static Decimal  stimaAterminareTot;
	private static integer  nRecord;


	public static void setCommonData(){
		AggregateResult aR = Database.query(baseQuery + whereClausole);
		System.debug(baseQuery + whereClausole);
		System.debug(aR);
		gratestDate = (date)aR.get('gratestDate');
		smallestDate = (date)aR.get('smallestDate');
		if(smallestDate< date.today() || smallestDate == gratestDate){
			smallestDate = date.today();
		}
		stimaAterminareTot = (decimal)ar.get('stimaAterminareTot');
		nRecord = (integer)aR.get('nRecord');

		if(Test.isRunningTest()) {
			gratestDate = Date.today().addDays(30);
			smallestDate = Date.today();
			stimaAterminareTot = 5;
			nRecord = 5;
		}
	}
	
	public static integer getHoliday(date smallestDate,date gratestDate){
		return [Select count() From Holiday where ActivityDate >= : smallestDate AND ActivityDate <= :gratestDate];
	}
	
	public static integer getWeekDay(Date smallestDate,Date gratestDate){
		System.debug('Data minore: '+smallestDate+' *** data maggiore: '+gratestDate );
		integer weekDay = 0;
		Integer allDaysBetween = smallestDate.daysBetween(gratestDate);
		System.debug('****** all days between'+allDaysBetween);
		Date startdt = Date.today();
		for(Integer i =0; i<allDaysBetween; i++){
			Date weekStart = startdt.toStartofWeek().addDays(-1);
			if(weekStart.daysBetween(startdt) == 6 || weekStart.daysBetween(startdt) == 7){
				weekDay++;
			}
			startdt = startdt+1;
		}
		return weekDay;
	}
	
 
	public static void CalculateTotalFTE(){
		if(String.isBlank(whereClausole)){
			throw new customException('whereClausole dont null!');
		}
		setCommonData();
		Integer allDaysBetween = smallestDate.daysBetween(gratestDate)/2;
		Integer allWorkingDays = allDaysBetween-getHoliday(smallestDate, gratestDate)-getweekDay(smallestDate,gratestDate);
		Decimal FTE= stimaAterminareTot / allWorkingDays;
		Decimal MediaFTE = FTE / nRecord;
		System.debug(FTE+'   '+nRecord);
		System.debug('MediaFTE'+MediaFTE);
		List<ProjectStatus__c> PSupdate = Database.query('SELECT Id, AverageFTE__c FROM ProjectStatus__c WHERE RecordType.DeveloperName = \'Nexus\' AND '+whereClausole);
		for(ProjectStatus__c ps2: PSupdate){
			ps2.AverageFTE__c = MediaFTE;
		}
			
		update PSupdate;
	}
	
	public static void setDataAggiornamento(ProjectStatus__c newProject, ProjectStatus__c oldProject){
		boolean updateData = false;
		List<String> checkFields = changeFieldsCheck.split(',');
		for(String field: checkFields){
			try{
				updateData = updateData || (newProject.get(field) != oldProject.get(field));
			}
			catch(Exception e){
				throw new customException('The field '+ field +' does not exist check the CustomMetadata ProjectSetting__mdt' );
			}
		}
		if(updateData){
			newProject.UpdateDate__c = (Date) System.today();
		}
	}

	public void setAccountAndReferenceNumber(ProjectStatus__c projectStatus){
		projectStatus.Account__c = opportunityMap.get(projectStatus.Opportunity__c).AccountId;
		if(String.isBlank(projectStatus.ReferenceNumber__c)){
			projectStatus.ReferenceNumber__c = opportunityMap.get(projectStatus.Opportunity__c).ReferenceNumber__c;
		}
		if(!String.IsBlank(opportunityMap.get(projectStatus.Opportunity__c).DeliveryProjectManager__r.Email)){
			projectStatus.EmailNotification__c = opportunityMap.get(projectStatus.Opportunity__c).DeliveryProjectManager__r.Email;
		}else{
			projectStatus.EmailNotification__c = DefaultDeliveryManagerEmail;
		}
	}
	
	public static void CalculateDaysDiffExcludingHoliday(){
		setCommonData();
		List<ProjectStatus__c> ProjStatusList = [SELECT id,Name,ExpectedEndDate__c, RemainingFTE__c,BudgetDD__c,UpdateDate__c From ProjectStatus__c
												WHERE Opportunity__r.StageName = 'Closed Won' and Type__c = 'Progetto' and Stage__c !='Completato' and Opportunity__r.Account.Name != 'Banca Mediolanum Spa' AND RecordType.DeveloperName = 'Nexus'];
		for (ProjectStatus__c ps : ProjStatusList){
			if(ps.ExpectedEndDate__c != null){
				Date startdt = Date.today();
				Integer allDaysBetween = startdt.daysBetween(ps.ExpectedEndDate__c)+1;
				Integer allWorkingDays= allDaysBetween-getHoliday(startdt, ps.ExpectedEndDate__c)-getWeekDay(startdt, ps.ExpectedEndDate__c);
				System.debug('data di fine prevista: '+ps.ExpectedEndDate__c+' nome: '+ps.Name+ '*****'+getWeekDay(startdt, ps.ExpectedEndDate__c));
				ps.RemainingFTE__c = allWorkingDays < 0 ? 0 : allWorkingDays;
			}else {
				ps.RemainingFTE__c = null;
			}
		}
		update ProjStatusList;
	}  
}