force-app/main/default/objects/Account/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <businessProcess>Links Sales Process</businessProcess>
    <label>Links Management Technologies</label>
</RecordType>

force-app/main/default/objects/Pricebook2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Manages the execution of the Apex Trigger</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterDelete__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterDelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterInsert__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterUpdate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineItemTriggerHelperTest.cls
@isTest
private class QuoteLineItemTriggerHelperTest {
    
    private static String name = 'Costi Risorse Umane Links';
    
    public static String getRecordTypeId(String sobjectName, String recordTypeName){
		return Schema.getGlobalDescribe().get(sobjectName).getDescribe().getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
	}

    @TestSetup
    static void makeData(){
        List<TriggerSetting__mdt> customMetaData = createCustomMetadata(true);
        Account account = new Account (RecordTypeId = TestDataFactory.getRecordTypeId('Account','Nexus'),Name=name);
        insert account;
        Product2 prod = new Product2(Name = 'Intern 2021',
                                     Family = 'Standard',
                                     ProductCoDe = 'IN',
                                     IsActive = true);
        insert prod;
        /********************************************************************** */
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = prod.Id,
            UnitPrice = 10000, 
            IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Costi Risorse Umane Links', 
                                             isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, 
            Product2Id = prod.Id,
            UnitPrice = 12000, 
            IsActive = true);
        insert customPrice;
        //***************************************************************************** */
        
        Opportunity opportunity = new Opportunity (RecordTypeId = getRecordTypeId('Opportunity','Links'),Name=name,AccountId=account.Id,CloseDate=Date.today(),StageName='Prospecting',Pricebook2Id=customPB.Id);
        insert opportunity;
        
        Quote quote = new Quote(RecordTypeId = getRecordTypeId('Quote','Links'),Name=name,OpportunityId = opportunity.id);
        insert quote;
        
    }
    
    
    private static List<TriggerSetting__mdt> createCustomMetadata(Boolean status) {
        List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
            '[' +
            '{' +
            '"DeveloperName": "Links",' +
            '"QuoteLineItemAfterDelete__c": "' + status + '"' +
            '}' +
            ']' +
            '[' +
            '{' +
            '"DeveloperName": "Links",' +
            '"QuoteLineItemAfterInsert__c": "' + status + '"' +
            '}' +
            ']' +
            '[' +
            '{' +
            '"DeveloperName": "Links",' +
            '"QuoteLineItemAfterUpdate__c": "' + status + '"' +
            '}' +
            ']'
            ,List<TriggerSetting__mdt>.class
        ); 
        return triggerSettingMDT;
    }
    @isTest
    private static void quoteLineItemUpdateTotalHRCostTEST(){
        Test.startTest();
        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
        for(Integer i=0;i<10;i++){
            QuoteLineItem q = new QuoteLineItem();
            q.QuoteId = [SELECT id FROM Quote WHERE name =: name LIMIT 1].id;
            q.PricebookEntryId = [SELECT id FROM PricebookEntry WHERE PriceBook2.Name =: name LIMIT 1].Id;
            q.Quantity = 1;
            q.Revenue_Type__c = '6';
            q.UnitPrice = 100;
            quoteLineItemList.add(q);
        }
        insert quoteLineItemList;
        update quoteLineItemList;
        delete quoteLineItemList;
        Test.stopTest();
        
    }
    
}