force-app/main/default/objects/Account/fields/Acronimo__c.field-meta.xml
<CustomField>
    <fullName>Acronimo__c</fullName>
    <label>Acronimo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/Invoice_Milestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Milestone__c/fields/Ammontare__c.field-meta.xml
<CustomField>
    <fullName>Ammontare__c</fullName>
    <label>Ammontare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Anno__c.field-meta.xml
<CustomField>
    <fullName>Anno__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>Anno della fattura.</description>
    <label>Anno</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Data_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_prevista__c</fullName>
    <label>Data prevista</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Numero_Ordine_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Numero_Ordine_del_Cliente__c</fullName>
    <label>Numero Ordine del Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices Milestone</relationshipLabel>
    <relationshipName>Billing_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/recordTypes/One_Shot.recordType-meta.xml
<RecordType>
    <fullName>One_Shot</fullName>
    <active>true</active>
    <label>One Shot</label>
</RecordType>

force-app/main/default/objects/Invoice_Milestone__c/recordTypes/Recursive.recordType-meta.xml
<RecordType>
    <fullName>Recursive</fullName>
    <active>true</active>
    <label>Recursive</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Numero_Ordine_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Numero_Ordine_del_Cliente__c</fullName>
    <label>Numero Ordine del Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schema di Fatturazione</label>
    <referenceTo>Tipo_Pagamento__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento__c/Tipo_Pagamento__c.object-meta.xml
<CustomObject>
    <label>Schema di fatturazione</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo Pagamenti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_Pagamento__c/fields/isDeleted__c.field-meta.xml
<CustomField>
    <fullName>isDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDeleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recursive</fullName>
            </value>
            <value>
                <fullName>One Shot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/Tipo_Pagamento_Dettaglio__c.object-meta.xml
<CustomObject>
    <label>Schema di fatturazione Dettaglio</label>
    <nameField>
        <label>Tipo Pagamento Dettaglio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo Pagamento Dettagli</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Descrizione__c.field-meta.xml
<CustomField>
    <fullName>Descrizione__c</fullName>
    <label>Descrizione</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Numero_Canoni__c.field-meta.xml
<CustomField>
    <fullName>Numero_Canoni__c</fullName>
    <label>Numero Canoni</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Tipo_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Pagamento__c</fullName>
    <label>Schema di fatturazione</label>
    <referenceTo>Tipo_Pagamento__c</referenceTo>
    <relationshipLabel>Schema di fatturazione Dettagli</relationshipLabel>
    <relationshipName>Tipo_Pagamento_Dettagli</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Unit_di_misura__c.field-meta.xml
<CustomField>
    <fullName>Unit_di_misura__c</fullName>
    <label>Unità di misura (Mensile)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Valore__c.field-meta.xml
<CustomField>
    <fullName>Valore__c</fullName>
    <label>Valore %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tipo_Pagamento_Dettaglio__c/fields/Valore_Canone__c.field-meta.xml
<CustomField>
    <fullName>Valore_Canone__c</fullName>
    <label>Valore Canone</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PianificazioneFattureController.cls
public class PianificazioneFattureController {
    //Called from Proces Builder
    @InvocableMethod
    public static void createInvoiceMilestoneInvocable(List<Id> listOppIds){
        
        for(Id oppId : listOppIds){
            createInvoiceMilestone(oppId);
        }
    }
    @AuraEnabled
    public static Boolean createInvoiceMilestone(Id recordId){
        List<Invoice_Milestone__c> imList = New List<Invoice_Milestone__c>();
        Boolean check = false;
        Id rtId = null;
        String imStringName = '';
        try{
            Opportunity opp = [SELECT Id, StageName, Name, CloseDate, Tipo_Pagamento__c, Reference_Number__c,Amount,Numero_Ordine_del_Cliente__c,Account.Acronimo__c,Account.Name
                                FROM Opportunity
                                WHERE Id =: recordId];
            deleteInvoiceMilestonePresenti(opp);
            //if(opp.StageName == 'Proposal/Price Quote' && opp.Tipo_Pagamento__c != null){
            if( opp.Tipo_Pagamento__c != null){                    
                    Double numCanoni;
                    Integer mensilit;
                    
                    Tipo_Pagamento__c tp = [SELECT Id, Tipo__c,Descrizione__c,isDeleted__c,Name
                                            FROM Tipo_Pagamento__c
                                            WHERE Id =: opp.Tipo_Pagamento__c];
                    
                    System.debug('Ø-opp.Tipo_Pagamento__c '+opp.Tipo_Pagamento__c);
                    
                    //Get Tipo di Pagamento dettaglio Object
                    List<Tipo_Pagamento_Dettaglio__c> tpdList = [SELECT Id, Name,Numero_Canoni__c,RecordTypeId,Tipo_Pagamento__c,Unit_di_misura__c,Valore__c,Valore_Canone__c,Rank__c
                                                                 FROM Tipo_Pagamento_Dettaglio__c
                                                                 WHERE Tipo_Pagamento__c =: opp.Tipo_Pagamento__c
                                                                 ORDER BY Rank__c ASC
                                                                ];
                    
                    //Get RecordType and Create Invoice Milestone
                    if(tp.Tipo__c == 'Recursive')
                    {
                        rtId = [SELECT Id, DeveloperName 
                                FROM RecordType 
                                WHERE DeveloperName = 'Recursive'].Id;
                        System.debug('Ø-rtId '+rtId);
                        
                        for(Tipo_Pagamento_Dettaglio__c tpd1 : tpdList){
                            numCanoni = tpd1.Numero_Canoni__c;
                            System.System.debug('Ø*** numero canoni: '+numCanoni);
                            mensilit = Integer.valueOf(tpd1.Unit_di_misura__c);
                            System.System.debug('Ø*** unità di misura: '+mensilit);
                            for(Integer i = 0; i< numCanoni; i++){
                                for(Tipo_Pagamento_Dettaglio__c tpd2 : tpdList){
                                    Invoice_Milestone__c im = New Invoice_Milestone__c();
                                    im.Opportunity__c = opp.Id;
                                    im.RecordTypeId = rtId;
                                    Date oppDate = opp.CloseDate;
                                    im.Data_prevista__c = oppDate.addMonths(mensilit*i);
                                    System.System.debug('Ø*** Invoice Milestone - Data prevista: '+im.Data_prevista__c);
                                    Integer monthNumber = im.Data_prevista__c.month();
                                    String monthName = '';
                                    if(monthNumber == 1)
                                        monthName = 'January';
                                    else if(monthNumber == 2)
                                        monthName = 'February';
                                    else if(monthNumber == 3)
                                        monthName = 'March';
                                    else if(monthNumber == 4)
                                        monthName = 'April';
                                    else if(monthNumber == 5)
                                        monthName = 'May';
                                    else if(monthNumber == 6)
                                        monthName = 'June';
                                    else if(monthNumber == 7)
                                        monthName = 'July';
                                    else if(monthNumber == 8)
                                        monthName = 'August';
                                    else if(monthNumber == 9)
                                        monthName = 'September';
                                    else if(monthNumber == 10)
                                        monthName = 'October';
                                    else if(monthNumber == 11)
                                        monthName = 'November';
                                    else if(monthNumber == 12)
                                        monthName = 'December';
                                    String yearName = String.valueof(im.Data_prevista__c.year());
                                    if(opp.Account.Acronimo__c != null){
                                        imStringName = String.valueOf(opp.Reference_Number__c)+' - '+ ' '+ opp.Account.Acronimo__c+' - '+tp.Name +' - '+monthName+' '+yearName;
                                    }else{
                                        imStringName = String.valueOf(opp.Reference_Number__c)+' - '+ ' '+ opp.Account.Name.left(3)+' - '+tp.Name +' - '+monthName+' '+yearName;
                                    }
                                    im.Name = imStringName;
                                    im.Ammontare__c = opp.Amount / tpd2.Numero_Canoni__c;
                                    im.Description__c = 'Servizio a Canone - '+opp.Name ;
                                    im.Numero_Ordine_del_Cliente__c = opp.Numero_Ordine_del_Cliente__c;
                                    im.Anno__c = yearName;
                                    System.System.debug('im.Numero_Ordine_del_Cliente__c');
                                    imList.add(im);		
                                }
                            }
                        }
                    }
                    
                    //Get RecordType and Create Invoice Milestone
                    if(tp.Tipo__c == 'One Shot')
                    {
                        rtId = [SELECT Id, DeveloperName 
                                FROM RecordType 
                                WHERE DeveloperName = 'One_Shot'].Id;
                        System.debug('Ø-rtId '+rtId);
                        
                        for(Tipo_Pagamento_Dettaglio__c tpd : tpdList){
                            Invoice_Milestone__c im = New Invoice_Milestone__c();
                            if(opp.Account.Acronimo__c != null ){
                                im.Name = String.valueOf(opp.Reference_Number__c)+' - '+ opp.Account.Acronimo__c+' - '+ tpd.Name;
                            }else{
                                im.Name = String.valueOf(opp.Reference_Number__c)+' - '+ opp.Account.Name.left(3)+' - '+ tpd.Name;
                            }                            
                            im.Rank__c = tpd.Rank__c;
                            im.Opportunity__c = opp.Id;
                            im.RecordTypeId = rtId;
                            im.Data_prevista__c = Date.today();
                            im.Anno__c = String.valueOf(Date.today().year());
                        	String yearName = String.valueof(im.Data_prevista__c.year());      ///**********************
                            im.Anno__c = String.valueOf(Date.today().year());
                            im.Anno__c = yearName;
                            im.Ammontare__c = (opp.Amount * tpd.Valore__c) / 100;
                            im.Description__c = tpd.Name +' - '+ opp.Name;
                            im.Numero_Ordine_del_Cliente__c = opp.Numero_Ordine_del_Cliente__c;
                            imList.add(im);		
                        }
                    }
                }
                if(!imList.isEmpty()){
            insert imList;
            check = true;
                }
        }catch(Exception ex){
        System.debug('Exception : '+ex+', message: '+ex.getMessage()+' - '+ex.getLineNumber()+' - '+ex.getCause());
        }
        return check;
    }
    //Delete Invoice Milestone
    @AuraEnabled
    public static void deleteInvoiceMilestonePresenti(Opportunity opp){

        List<Invoice_Milestone__c> invoiceMilestoneToDelete = [SELECT Id, Opportunity__c FROM Invoice_Milestone__c WHERE Opportunity__c =: opp.Id];

        if(!invoiceMilestoneToDelete.isEmpty()){
            delete invoiceMilestoneToDelete;
        }
    }
}