force-app/main/default/objects/Account/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExpectedPaymentsDays__c.field-meta.xml
<CustomField>
    <fullName>ExpectedPaymentsDays__c</fullName>
    <label>Expected Payments Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost__c/Cost__c.object-meta.xml
<CustomObject>
    <label>Cost</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost__c/fields/Cost_Type__c.field-meta.xml
<CustomField>
    <fullName>Cost_Type__c</fullName>
    <label>Cost Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Acquisto Hardware</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Acquisto Software</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Acquisto Servizi</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Trasferte</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Altri costi Diretti</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Utenze</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Canoni</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Ammortamenti</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Spese Varie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Cost_Value__c.field-meta.xml
<CustomField>
    <fullName>Cost_Value__c</fullName>
    <label>Cost Value (€)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/ExpectedPaymentsDays__c.field-meta.xml
<CustomField>
    <fullName>ExpectedPaymentsDays__c</fullName>
    <label>Expected Payments Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost__c/fields/TotalCostValue__c.field-meta.xml
<CustomField>
    <fullName>TotalCostValue__c</fullName>
    <formula>Cost_Value__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ApprovedDate__c.field-meta.xml
<CustomField>
    <fullName>ApprovedDate__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsMarginValid__c.field-meta.xml
<CustomField>
    <fullName>IsMarginValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Margin Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/isMinMarginValid__c.field-meta.xml
<CustomField>
    <fullName>isMinMarginValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Min Margin Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/LinksTotalHRCost__c.field-meta.xml
<CustomField>
    <fullName>LinksTotalHRCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total HR Cost</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Risk_Level__c</fullName>
    <formula>TEXT(Opportunity.Risk_Level__c)</formula>
    <label>Opportunity Risk Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Risk_Level_Description__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Risk_Level_Description__c</fullName>
    <formula>Opportunity.Risk_Level_Description__c</formula>
    <label>Opportunity Risk Level Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProtocolNumber__c.field-meta.xml
<CustomField>
    <fullName>ProtocolNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Protocol Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <summarizedField>Cost__c.TotalCostValue__c</summarizedField>
    <summaryForeignKey>Cost__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <label>Total Links Revenue</label>
    <summarizedField>Quote_Revenue__c.LinksRevenue__c</summarizedField>
    <summaryForeignKey>Quote_Revenue__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalQuotaATI__c.field-meta.xml
<CustomField>
    <fullName>TotalQuotaATI__c</fullName>
    <label>Total Quota ATI</label>
    <summarizedField>Quote_Revenue__c.QuotaATI__c</summarizedField>
    <summaryForeignKey>Quote_Revenue__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalRevenue__c.field-meta.xml
<CustomField>
    <fullName>TotalRevenue__c</fullName>
    <formula>Total_Revenue__c +  TotalQuotaATI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total Links Revenue + Total Quota ATI</inlineHelpText>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/Quote_Revenue__c.object-meta.xml
<CustomObject>
    <label>Quote Revenue</label>
    <nameField>
        <displayFormat>QRN-{000000}</displayFormat>
        <label>Quote Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Revenue__c/fields/BillSubject__c.field-meta.xml
<CustomField>
    <fullName>BillSubject__c</fullName>
    <label>Bill Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Quote__r.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/DocumentDate__c.field-meta.xml
<CustomField>
    <fullName>DocumentDate__c</fullName>
    <label>Document Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/LinksRevenue__c.field-meta.xml
<CustomField>
    <fullName>LinksRevenue__c</fullName>
    <label>Links Revenue (€)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/QuotaATI__c.field-meta.xml
<CustomField>
    <fullName>QuotaATI__c</fullName>
    <label>Quota ATI (€)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Revenues</relationshipLabel>
    <relationshipName>Quote_Revenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/TotalRevenue__c.field-meta.xml
<CustomField>
    <fullName>TotalRevenue__c</fullName>
    <formula>QuotaATI__c +  LinksRevenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DDOvernightAllowance__c.field-meta.xml
<CustomField>
    <fullName>DDOvernightAllowance__c</fullName>
    <label>DD Overnight Allowance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DDTotal__c.field-meta.xml
<CustomField>
    <fullName>DDTotal__c</fullName>
    <label>DD Total</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DDTotalCost__c.field-meta.xml
<CustomField>
    <fullName>DDTotalCost__c</fullName>
    <formula>Quantity *  DDTotal__c *  PricebookEntry.UnitPrice</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DD Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DDTravelAllowance__c.field-meta.xml
<CustomField>
    <fullName>DDTravelAllowance__c</fullName>
    <label>DD Travel Allowance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OvernightAllowanceCost__c.field-meta.xml
<CustomField>
    <fullName>OvernightAllowanceCost__c</fullName>
    <formula>Quantity *  DDOvernightAllowance__c *  PricebookEntry.OvernightAllowance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overnight Allowance Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TotalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalCost__c</fullName>
    <formula>OvernightAllowanceCost__c +  TravelAllowanceCost__c +   DDTotalCost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TotalCostHR__c.field-meta.xml
<CustomField>
    <fullName>TotalCostHR__c</fullName>
    <label>Total Cost HR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TravelAllowanceCost__c.field-meta.xml
<CustomField>
    <fullName>TravelAllowanceCost__c</fullName>
    <formula>Quantity *  DDTravelAllowance__c *  PricebookEntry.TravelAllowance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travel Allowance Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PagePDF.cls
/**
* @description       : Apex Controller for PDF Page
* @author            : Riccardo Costantini
* @last modified on  : 27--04-2021
* @last modified by  : 
* Modifications Log 
* Ver   Date         Author   Modification
* 0.5.1   14-04-2021   RC   Initial Version
* 0.6.0   27-04-2021   RC   Modifiche concettuali apportate relative al cambio algoritmico dell'Economic Plan
**/

public class PagePDF{
    //Get Quote Object
    public Quote getQuoteObj(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        Quote quoteObj = [SELECT Id, Name, Account.Name, Opportunity.Name, Description, IsMarginValid__c, isMinMarginValid__c, Opportunity_Risk_Level__c, 
                          EndDate__c, ProtocolNumber__c, StartDate__c, ApprovedDate__c, Total_Revenue__c, Opportunity_Risk_Level_Description__c,
                          Total_Cost__c, LinksTotalHRCost__c, TotalQuotaATI__c 
                          FROM Quote
                          WHERE Id = :idQuote];
        return quoteObj;
    } 
    
    //Get Quote Line Item
    public List<QuoteLineItem> getQuoteLineItem(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        List<QuoteLineItem> getQuoteLineItem = [SELECT Id, Product2.Name, Quantity, UnitPrice, Description,
                                                Revenue_Type__c, TotalCostHR__c, DDTotalCost__c, DDTotal__c, TotalCost__c, 
                                                OvernightAllowanceCost__c, TravelAllowanceCost__c, DDOvernightAllowance__c, DDTravelAllowance__c 
                                                FROM QuoteLineItem
                                                WHERE QuoteId = :idQuote];
        return getQuoteLineItem;
    } 
    
    
    //Get List of Cost
    public List<Cost__c> getCostObj(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        List<Cost__c> costObj = [SELECT Id, Cost_Type__c, Quote__r.Name, Quantity__c, Cost_Value__c,
                                 Description__c, Note__c, TotalCostValue__c, ExpectedPaymentsDays__c, DocumentDate__c, Revenue_Type__c 
                                 FROM Cost__c
                                 WHERE Quote__c = :idQuote];
        return costObj;
    }
    
    //Get List of Quote Revenue
    public List<Quote_Revenue__c> getQuoteRevenue(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        List<Quote_Revenue__c> getQuoteRevenue = [SELECT Revenue_Type__c, TotalRevenue__c, Customer__c, ExpectedPaymentsDays__c, 
                                                  QuotaATI__c, DocumentDate__c, Note__c, LinksRevenue__c, Quote__r.LinksTotalHRCost__c,
                                                  BillSubject__c, Quote__c, Name, Id 
                                                  FROM Quote_Revenue__c
                                                  WHERE Quote__c = :idQuote];

        return getQuoteRevenue;
    }
    
    public List<EconomicPlanController.EconomicPlan> getEconomicPlanPDF(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        return EconomicPlanController.getEconomicPlan(idQuote);
    }
    
    public EconomicPlanController.EconomicPlan getTotalEconomicPlanPDF(){
        String idQuote = ApexPages.currentPage().getParameters().get('id');
        return EconomicPlanController.getTotalEconomicPlan(idQuote);
    }
}