force-app/main/default/objects/Account/fields/DifferenceDay__c.field-meta.xml
<CustomField>
    <fullName>DifferenceDay__c</fullName>
    <label># Days Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/Invoice_Milestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices Milestone</relationshipLabel>
    <relationshipName>Billing_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Stato__c.field-meta.xml
<CustomField>
    <fullName>Stato__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleStatoPagamentoClienti.cls
global class ScheduleStatoPagamentoClienti implements Schedulable {
   
    global void execute(SchedulableContext ctx) {
      
      azzera();
      controlloFatturePagate();
  
      StatoPagamentoClienti spc = new StatoPagamentoClienti();
      Database.executebatch(spc);
    }
  
    private void azzera(){
      List<Account> accountReset = [SELECT Id,name,DifferenceDay__c FROM Account WHERE DifferenceDay__c != null]; 
      for(Account acc : accountReset){
        acc.DifferenceDay__c = null;
      }
      update accountReset;
    }
    private void controlloFatturePagate(){
      List <AggregateResult> accountCount = [SELECT  Opportunity__r.AccountId acc
                                              FROM Invoice_Milestone__c
                                              WHERE Stato__c = 'Fattura Pagata'
                                              GROUP BY Opportunity__r.AccountId];
  
                                              List<Account> accountSaldoOk = new List <Account>();
  
      for(AggregateResult agg : accountCount){
        Account a = new Account(
          Id = (id)agg.get('acc'),
          DifferenceDay__c = 0
        );
        accountSaldoOk.add(a);
      }
    }
  }