force-app/main/default/objects/Account/fields/DifferenceDay__c.field-meta.xml
<CustomField>
    <fullName>DifferenceDay__c</fullName>
    <label># Days Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/FattureInCloudSettings__c/FattureInCloudSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Informazioni per accesso a Fatture in Cloud via REST API.</description>
    <label>Fatture In Cloud Settings</label>
</CustomObject>

force-app/main/default/objects/FattureInCloudSettings__c/fields/InvoiceStage__c.field-meta.xml
<CustomField>
    <fullName>InvoiceStage__c</fullName>
    <label>Invoice Stage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Manages the execution of the Apex Trigger</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerSetting__mdt/fields/OpportunityBeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>OpportunityBeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/StatoPagamentoTest.cls
/**
 * @description       : 
 * @author            : 
 * @last modified on  : 02/02/2021
 * @last modified by  : ¤ → alessio.marra@nexusat.it
**/
@isTest
private class StatoPagamentoTest {

	private static List<TriggerSetting__mdt> createCustomMetadata(Boolean status) {
		List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
			'[' +
				'{' +
					'"DeveloperName": "Nexus",' +
					'"OpportunityBeforeInsert__c": "' + status + '"' +
				'}' +
			']'
			,List<TriggerSetting__mdt>.class
		); 
		return triggerSettingMDT;
	}

	@TestSetup
	static  void impostazioneDati(){
		String invoiceStage = 'Fattura Inviata';
		List<Account> lstAccount = new List<Account>(); //lista account
		List<Opportunity> lstOpportunity = new List<Opportunity>(); //lista opportunity 
		List<InvoiceMilestone__c> lstInvoiceMilestone = new List<InvoiceMilestone__c>(); //lista Invoice Milestone
		FattureInCloudSettings__c fattureInCloudeSettings = new FattureInCloudSettings__c();
		fattureInCloudeSettings.InvoiceStage__c = invoiceStage;

		insert fattureInCloudeSettings;

		Account acc = new Account();
		acc.Name = 'Name Test';
		acc.DifferenceDay__c = 20;
		insert acc;

		Opportunity opp = new Opportunity();
		opp.AccountId = acc.id;
		opp.Name = 'Opportunity Test';
		opp.StageName = 'Prospecting';
		opp.CloseDate = Date.today();
		insert opp;
		
		InvoiceMilestone__c inv = new InvoiceMilestone__c();
		inv.Name = 'Invoice Test';
		inv.ExpectedDate__c = Date.today().addDays(-1);
		inv.Stage__c = invoiceStage;
		inv.Opportunity__c = opp.id;
		insert inv;
	}

	@isTest
	static  void eseguiTest(){
		Test.startTest();
		TriggerUtilities.TriggerSettingOpportunity = createCustomMetadata(true);
		StatoPagamentoClienti obj = new StatoPagamentoClienti();
		DataBase.executeBatch(obj); 
		Test.stopTest();
	}
}