force-app/main/default/objects/Account/fields/DifferenceDay__c.field-meta.xml
<CustomField>
    <fullName>DifferenceDay__c</fullName>
    <label># Days Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleStatoPagamentoTest.cls
@isTest
private class ScheduleStatoPagamentoTest{

	public ScheduleStatoPagamentoTest(){}

	@TestSetup
	static  void impostazioneDati(){

		List<Account> lstAccount = new List<Account>(); //lista account
		List<Opportunity> lstOpportunity = new List<Opportunity>(); //lista opportunity 
		List<InvoiceMilestone__c> lstInvoiceMilestone = new List<InvoiceMilestone__c>(); //lista Invoice Milestone

	   

		//Valorizzo una lista di 200 account
		for(Integer i=0 ;i <200;i++){
			Account acc = new Account();
			acc.Name ='Name'+i;
			acc.DifferenceDay__c = 20 ;
			lstAccount.add(acc);
		}
		insert lstAccount;   

		 //ciclo la lista di account e per ognuno di essi inserisco le opportunity
		for(Account ac : lstAccount){     
			for(Integer i=0 ;i <3;i++){
				Opportunity opp1 = new Opportunity();
					opp1.AccountId = ac.id;
					opp1.Name = 'oppTest'+ i;
					opp1.StageName = 'Prospecting' + i;
					opp1.CloseDate = Date.today();
					lstOpportunity.add(opp1);
			}
		}
		insert lstOpportunity;
		
		//ciclo la lista di opportunity e per ognuna di esse inserisco le invoice milestone
		for(Opportunity opp: lstOpportunity){
			for(Integer i=0 ;i <3;i++){
				InvoiceMilestone__c inv = new InvoiceMilestone__c();
				inv.Name = 'intTest' + i;
				inv.ExpectedDate__c = Date.today() - 1;
				inv.Stage__c = 'Fattura Pagata';
				inv.Opportunity__c = opp.id;
				lstInvoiceMilestone.add(inv);
			}
		}
		insert lstInvoiceMilestone;
	}
	@isTest
	static  void eseguiTest(){
		Test.startTest();
		ScheduleStatoPagamentoClienti obj = new ScheduleStatoPagamentoClienti();
		String chron = '0 0 23 * * ?';        
		System.schedule('Test Sched', chron, obj);
		Test.stopTest();
	}
}