force-app/main/default/objects/Account/fields/DifferenceDay__c.field-meta.xml
<CustomField>
    <fullName>DifferenceDay__c</fullName>
    <label># Days Overdue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroInvoiceNonPagato__c.field-meta.xml
<CustomField>
    <fullName>NumeroInvoiceNonPagato__c</fullName>
    <label>Numero Invoice Non Pagato</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FattureInCloudSettings__c/FattureInCloudSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Informazioni per accesso a Fatture in Cloud via REST API.</description>
    <label>Fatture In Cloud Settings</label>
</CustomObject>

force-app/main/default/objects/FattureInCloudSettings__c/fields/StatoFattura__c.field-meta.xml
<CustomField>
    <fullName>StatoFattura__c</fullName>
    <label>StatoFattura</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/Invoice_Milestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Milestone__c/fields/Data_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_prevista__c</fullName>
    <label>Data prevista</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices Milestone</relationshipLabel>
    <relationshipName>Billing_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Milestone__c/fields/Stato__c.field-meta.xml
<CustomField>
    <fullName>Stato__c</fullName>
    <label>Stato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatoPagamentoClienti.cls
global class StatoPagamentoClienti implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Name , NumeroInvoiceNonPagato__c FROM Account');
        // collect the batches of records or objects to be passed to execute  
    }

    global void execute(Database.BatchableContext bc, List<Account> scope){ // process each batch of records
        
        String whereClausole = FattureInCloudSettings__c.getOrgDefaults().StatoFattura__c; 
        Map<Id, Account> accountMap = new Map<Id, Account>(scope);
        
        List <AggregateResult> accountCount = [SELECT  Opportunity__r.AccountId acc, min(Data_Prevista__c) dtp
        FROM Invoice_Milestone__c
        WHERE Stato__c =: whereClausole and Data_Prevista__c < Today
        GROUP BY Opportunity__r.AccountId];

       
        if(accountCount.size() > 0){           
            for(AggregateResult agg:accountCount){
                Account acc = accountMap.get((id)agg.get('acc')); //prende Id dei vari account 
                if(acc != null){
                 acc.DifferenceDay__c = calculateDifferce((Date)agg.get('dtp')); //inserisce i giorni di differenza tra la data prevista ed oggi
                }
            }
        }
        
        if(accountMap.size() > 0){
            try{
                update accountMap.values();
            }catch(DmlException e){
                System.debug('*** The following exception has occurred: ' + e.getMessage());
            }
        }
    }

    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }    

    //Calcola la differenza dei giorni dalla data previst a quella odierna 
    public Integer calculateDifferce(Date dataPrevista){   
         return dataPrevista.daysBetween(Date.Today());
    }
}