force-app/main/default/objects/Account/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Type</label>
    <referenceTo>PaymentType__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <businessProcess>Links Sales Process</businessProcess>
    <label>Links Management Technologies</label>
</RecordType>

force-app/main/default/objects/PaymentType__c/PaymentType__c.object-meta.xml
<CustomObject>
    <label>Payment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentType__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recursive</fullName>
            </value>
            <value>
                <fullName>One Shot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PaymentType__c/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>false</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/PaymentType__c/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricebook2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/RevenueTypesCS__c/RevenueTypesCS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Revenue Types CS</label>
</CustomObject>

force-app/main/default/objects/RevenueTypesCS__c/fields/DefaultMargin__c.field-meta.xml
<CustomField>
    <fullName>DefaultMargin__c</fullName>
    <label>Default Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RevenueTypesCS__c/fields/MinMargin__c.field-meta.xml
<CustomField>
    <fullName>MinMargin__c</fullName>
    <label>Min Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CreateIntranetQuote_test.cls
/**
 * @description       : 
 * @author            : francesco.coli@nexusat.it
 * @last modified on  : 19/09/2022
 * @last modified by  : francesco.coli@nexusat.it
**/
@isTest
public class CreateIntranetQuote_test{

    @TestSetup
    static void makeData(){
        IntranetQuoteGeneration__c custSettings = new IntranetQuoteGeneration__c(
            PriceBookName__c = 'Links2022',
            ProductCode__c = 'CS',
            ProductName__c = 'Consultant',
            RevenueType__c = '6'
        );
        insert custSettings;

        Account account = new Account(
            Name = 'TestAcc',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId()
        );
        insert account;

        Product2 productt = new Product2(
            Name = 'Consultant',
            ProductCode = 'CS',
            IsActive = true
        );
        insert productt;

        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = productt.Id,
            UnitPrice = 10000,
            IsActive = true);
        insert standardPrice;
 
        PaymentType__c paymentType = new PaymentType__c(
            Name = '100% allordine',
            Type__c = 'One Shot',
            RecordTypeId = Schema.SObjectType.PaymentType__c.getRecordTypeInfosByName().get('Nexus').getRecordTypeId()
        );
        insert paymentType;

        Opportunity opportunity = new Opportunity(
            Name = 'test123',
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Nexus').getRecordTypeId(),
            AccountId = account.Id,
            CloseDate = Date.today(),
            StageName = 'Qualification',
            Amount = 20000,
            PaymentType__c = paymentType.Id
        );
        insert opportunity;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Links 2022',
            ExtId__c = 'Links2022',
            RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByName().get('Links').getRecordTypeId()
        );
        insert pricebook;

        PricebookEntry pricebookentry = new PricebookEntry(
            Pricebook2Id = pricebook.Id,
            Product2Id = productt.Id,
            UnitPrice = 175,
            IsActive = true,
            UseStandardPrice = false
        );
        insert pricebookentry;

        RevenueTypesCS__c revenuetypecs = new RevenueTypesCS__c(
            DefaultMargin__c = 35,
            Name = 'Fixed-Price Projects/Services',
            MinMargin__c = 32
        );
        insert revenuetypecs;       
    }
    @isTest 
    public static void testUploadFile (){
        String base64 = EncodingUtil.base64Encode(Blob.valueof('teststring'));
        String filename = 'Test name 123';
        String recordId = [SELECT Id FROM Opportunity LIMIT 1].Id;


        test.startTest();
        createIntranetQuote.uploadFile(base64, filename, recordId);
        test.stopTest();

        }


}