force-app/main/default/objects/Account/fields/PriceBook__c.field-meta.xml
<CustomField>
    <fullName>PriceBook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Cost__c/Cost__c.object-meta.xml
<CustomObject>
    <label>Cost</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost__c/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <businessProcess>Links Sales Process</businessProcess>
    <label>Links Management Technologies</label>
</RecordType>

force-app/main/default/objects/Pricebook2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Nexus.recordType-meta.xml
<RecordType>
    <fullName>Nexus</fullName>
    <active>true</active>
    <label>Nexus</label>
</RecordType>

force-app/main/default/objects/Quote_Revenue__c/Quote_Revenue__c.object-meta.xml
<CustomObject>
    <label>Quote Revenue</label>
    <nameField>
        <displayFormat>QRN-{000000}</displayFormat>
        <label>Quote Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Revenue__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Revenues</relationshipLabel>
    <relationshipName>Quote_Revenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/recordTypes/Links.recordType-meta.xml
<RecordType>
    <fullName>Links</fullName>
    <active>true</active>
    <label>Links</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RevenueTypesCS__c/RevenueTypesCS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Revenue Types CS</label>
</CustomObject>

force-app/main/default/objects/RevenueTypesCS__c/fields/DefaultMargin__c.field-meta.xml
<CustomField>
    <fullName>DefaultMargin__c</fullName>
    <label>Default Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RevenueTypesCS__c/fields/MinMargin__c.field-meta.xml
<CustomField>
    <fullName>MinMargin__c</fullName>
    <label>Min Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Manages the execution of the Apex Trigger</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>QuoteAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>QuoteAfterUpdate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>QuoteAfterUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterDelete__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterDelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterInsert__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/QuoteLineItemAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemAfterUpdate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Quote Line Item After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EconomicPlanControllerTest.cls
/**
 * @description       : 
 * @author            : Œ - Mirco Centrone
 * @last modified on  : 30-07-2021
 * @last modified by  : Œ
 * Modifications Log 
 * Ver   Date         Author   Modification
 * 1.0   15-07-2021   Œ   Initial Version
**/
@IsTest
public with sharing class EconomicPlanControllerTest {
    
    private static List<TriggerSetting__mdt> createCustomMetadata(Boolean status) {
		List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
			'[' +
				'{' +
					'"DeveloperName": "Links",' +
					'"QuoteLineItemAfterDelete__c": "' + status + '"' +
				'}' +
			']' +
            '[' +
				'{' +
					'"DeveloperName": "Links",' +
					'"QuoteLineItemAfterInsert__c": "' + status + '"' +
				'}' +
			']' +
            '[' +
				'{' +
					'"DeveloperName": "Links",' +
					'"QuoteLineItemAfterUpdate__c": "' + status + '"' +
				'}' +
			']'
			,List<TriggerSetting__mdt>.class
		); 
		return triggerSettingMDT;
	}

    
    private static List<TriggerSetting__mdt> createQuoteCustomMetadata(Boolean status) {
        List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
            '[' +
				'{' +
					'"DeveloperName": "Nexus",' +
					'"QuoteAfterInsert__c": "' + status + '",' +
					'"QuoteAfterUpdate__c": "' + status + '"' +
				'},' +
				'{' +
					'"DeveloperName": "Links",' +
					'"QuoteAfterInsert__c": "' + status + '",' +
					'"QuoteAfterUpdate__c": "' + status + '"' +
				'}' +
            ']'
            ,List<TriggerSetting__mdt>.class
        ); 
        return triggerSettingMDT;
    }

    private static String name = 'Test9956';

    public static String getRecordTypeId(String sobjectName, String recordTypeName){
		return Schema.getGlobalDescribe().get(sobjectName).getDescribe().getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
	}

    @TestSetup
    static void makeData(){
        TriggerUtilities.TriggerSettingQuoteLineItem = createCustomMetadata(false);
        TriggerUtilities.TriggerSettingQuote = createQuoteCustomMetadata(false);
        
        Product2 prod = new Product2(Name = 'Intern 2021',
                                     Family = 'Standard',
                                     ProductCoDe = 'IN',
                                     IsActive = true);
        insert prod;
        /********************************************************************** */
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, 
            Product2Id = prod.Id,
            UnitPrice = 10000, 
            IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Costi Risorse Umane Links', 
                                             isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, 
            Product2Id = prod.Id,
            UnitPrice = 12000, 
            IsActive = true);
        insert customPrice;
        
        Account account = new Account (RecordTypeId = getRecordTypeId('Account','Customer'),Name=name, Pricebook__c = customPB.Id );
        insert account;

        Opportunity opportunity = new Opportunity (RecordTypeId = getRecordTypeId('Opportunity','Links'),Name=name,AccountId=account.Id,CloseDate=Date.today(),StageName='Prospecting',Pricebook2Id=customPB.Id);
        insert opportunity;

		//Insert Quote
		Quote quoteTest = New Quote();
		quoteTest.Name = name;
		quoteTest.OpportunityId = opportunity.id;
		quoteTest.Status = '0';
		quoteTest.RecordTypeId = getRecordTypeId('Quote', 'Links');
        quoteTest.Pricebook2Id = Test.getStandardPricebookId();
		insert quoteTest;

        Product2 p2 = new Product2(Name = 'Intern 2021',
                                    Family = 'Standard',
                                    ProductCoDe = 'IN',
                                    IsActive = true);
        insert p2;
        PricebookEntry pb = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(), 
            Product2Id = p2.Id,
            UnitPrice = 10000, 
            IsActive = true);
        insert pb;
        QuoteLineItem con = new QuoteLineItem(QuoteId = quoteTest.id, PricebookEntryId = pb.id, Quantity = 1, Revenue_Type__c = '6' , UnitPrice = 1000 );
        insert con;
        Cost__c  cost = new Cost__c(Quote__c = quoteTest.id, Revenue_Type__c = '6');
        insert cost;
        Quote_Revenue__c  quoteRevenue = new Quote_Revenue__c(Quote__c = quoteTest.id, Revenue_Type__c = '6');
        insert quoteRevenue;
    }


    @IsTest
    static void getEconomicPlanTest(){
       
        RevenueTypesCS__c rtCS = new RevenueTypesCS__c();
        rtCS.Name = 'Prestazioni di Servizi';
        rtCS.DefaultMargin__c = 30;
        rtCS.MinMargin__c = 20;
        insert rtCS;
        
        Test.startTest();
        EconomicPlanController.getTotalEconomicPlan([SELECT id FROM Quote WHERE Name=: name LIMIT 1].id);
        Test.stopTest();
        delete [SELECT id FROM Quote WHERE Name=: name LIMIT 1];
    }
    @IsTest
    static void getEconomicPlanTestFAIL(){
       
        Test.startTest();
        try{
        EconomicPlanController.getTotalEconomicPlan([SELECT id FROM Quote WHERE Name=: name LIMIT 1].id);
        }
        catch(NullPointerException e){

        }
        Test.stopTest();
        delete [SELECT id FROM Quote WHERE Name=: name LIMIT 1];
    }
    @IsTest
    static void setQuoteIsMarginValidTEST(){
        
        EconomicPlanController.CustomWrapper cw = new EconomicPlanController.CustomWrapper();
        cw.quoteId = [SELECT id FROM Quote WHERE Name=: name LIMIT 1].id;
        cw.marginCheck = true;
        cw.totalMarginCheck = true;
        cw.costHRMargin = 100000;
        cw.costMargin = 100000;

        Test.startTest();
        EconomicPlanController.setQuoteIsMarginValid(cw);
        Test.stopTest();
        delete [SELECT id FROM Quote WHERE Name=: name LIMIT 1];
    }

}