force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentAlyante__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>ToBeEmitted</fullName>
                <label>To Be Emitted</label>
            </value>
            <value>
                <fullName>Emitted</fullName>
            </value>
            <value>
                <fullName>ToBePayed</fullName>
                <label>To Be Payed</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>PaidPartly</fullName>
                <label>Paid Partly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/recordTypes/ActiveInvoice.recordType-meta.xml
<RecordType>
    <fullName>ActiveInvoice</fullName>
    <active>true</active>
    <label>Active Invoice</label>
</RecordType>

force-app/main/default/objects/DocumentAlyante__c/recordTypes/CreditNote.recordType-meta.xml
<RecordType>
    <fullName>CreditNote</fullName>
    <active>false</active>
    <label>Credit Note</label>
</RecordType>

force-app/main/default/objects/DocumentAlyante__c/recordTypes/PassiveInvoice.recordType-meta.xml
<RecordType>
    <fullName>PassiveInvoice</fullName>
    <active>false</active>
    <label>Passive Invoice</label>
</RecordType>

force-app/main/default/objects/DocumentAlyante__c/recordTypes/PreInvoice.recordType-meta.xml
<RecordType>
    <fullName>PreInvoice</fullName>
    <active>true</active>
    <label>Pre Invoice</label>
</RecordType>

force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/recordTypes/Final.recordType-meta.xml
<RecordType>
    <fullName>Final</fullName>
    <active>true</active>
    <label>Final</label>
</RecordType>

force-app/main/default/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Manages the execution of the Apex Trigger</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerSetting__mdt/fields/DocumentAlyanteAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyanteAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DocumentAlyanteAfterInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/DocumentAlyanteAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyanteAfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DocumentAlyanteAfterUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSetting__mdt/fields/DocumentAlyanteBeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>DocumentAlyanteBeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DocumentAlyanteBeforeUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OnDocumentAlyanteTest.cls
/**
 * @description       : 
 * @author            : §
 * @group             : 
 * @last modified on  : 18/02/2022
 * @last modified by  : ¤ → alessio.marra@nexusat.it
**/
@isTest
public class OnDocumentAlyanteTest {
	private static final Id PRE_INVOICE_RT = getDocumentRecordTypeIdByDeveloperName('PreInvoice');
	private static final Id PASSIVE_INVOICE_RT = getDocumentRecordTypeIdByDeveloperName('PassiveInvoice');
	private static final Id CREDIT_NOTE_RT = getDocumentRecordTypeIdByDeveloperName('CreditNote');
	private static final Id ACTIVE_INVOICE_RT = getDocumentRecordTypeIdByDeveloperName('ActiveInvoice');

	@TestSetup static void makeData() {
		User testUser = createUser();
		insert testUser;

		Account testAccount = createAccount('Test Account');
		insert testAccount;

		DocumentAlyante__c creditNote = createDocumentAlyante('Emitted', testAccount.Id, CREDIT_NOTE_RT);
		DocumentAlyante__c passiveInvoice = createDocumentAlyante('Emitted', testAccount.Id, PASSIVE_INVOICE_RT);
		DocumentAlyante__c preInvoice = createDocumentAlyante('Draft', testAccount.Id, PRE_INVOICE_RT);

		insert new List<DocumentAlyante__c> {creditNote, passiveInvoice, preInvoice};
		Approval.unlock(creditNote.Id);
	}

	@isTest static void documentInsertTest() {
		TriggerUtilities.TriggerSettingDocumentAlyante = createCustomMetadata(true);
		User u = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
		Id accountId = [SELECT Id FROM Account LIMIT 1].Id;

		DocumentAlyante__c activeInvoice = createDocumentAlyante('Emitted', accountId, ACTIVE_INVOICE_RT);

		System.runAs(u) {
			Test.startTest();
			insert activeInvoice;
			Test.stopTest();
		}

		System.assert(Approval.isLocked(activeInvoice.Id));
	}

	@isTest static void creditNoteUpdateTest() {
		TriggerUtilities.TriggerSettingDocumentAlyante = createCustomMetadata(true);
		User u = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];

		DocumentAlyante__c creditNote = [SELECT Id, Status__c FROM DocumentAlyante__c WHERE RecordTypeId = :CREDIT_NOTE_RT LIMIT 1];
		creditNote.Status__c = 'Payed';

		System.assert(!Approval.isLocked(creditNote.Id));

		System.runAs(u) {
			Test.startTest();
			update creditNote;
			Test.stopTest();
		}

		System.assert(Approval.isLocked(creditNote.Id));
	}

	// @isTest static void passiveInvoiceTest() {
	// 	TriggerUtilities.TriggerSettingDocumentAlyante = createCustomMetadata(true);
	// 	User u = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];

	// 	DocumentAlyante__c passiveInvoice = [SELECT Id, Status__c FROM DocumentAlyante__c WHERE RecordTypeId = :PASSIVE_INVOICE_RT LIMIT 1];
	// 	passiveInvoice.Status__c = 'Payed';

	// 	System.runAs(u) {
	// 		Test.startTest();
	// 		try {
	// 			update passiveInvoice;
	// 			System.assert(false);
	// 		} catch(Exception e) {
	// 			System.assert(true);
	// 		}
			
	// 		Test.stopTest();
	// 	}
	// }

	
	@isTest static void preInvoiceWithoutDetailsTest() {
		TriggerUtilities.TriggerSettingDocumentAlyante = createCustomMetadata(true);

		DocumentAlyante__c preInvoice = [SELECT Id, Status__c FROM DocumentAlyante__c WHERE RecordTypeId = :PRE_INVOICE_RT LIMIT 1];
		preInvoice.Status__c = 'ToBeEmitted';

		List<AggregateResult> groupedResults = [SELECT count(Id) c FROM DocumentDetailAlyante__c WHERE Document__c = :preInvoice.Id];
		System.assert(groupedResults[0].get('c') == 0);

		Test.startTest();
		try {
			update preInvoice;
			System.assert(false);
		} catch(Exception e) {
			System.assert(true);
		}
		
		Test.stopTest();
	}



	private static User createUser() {
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
		String username = 'testuser@test' + Math.round(Math.random() * 10000) + '.com';

		return new User(
			Alias = 'standt',
			Email = username,
			EmailEncodingKey = 'UTF-8',
			LastName = 'Testing',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			ProfileId = p.Id,
			TimeZoneSidKey = 'America/Los_Angeles',
			UserName = username
		);
	}

	private static Id getDocumentRecordTypeIdByDeveloperName(String rtDeveloperName) {
		return Schema.sObjectType.DocumentAlyante__c.getRecordTypeInfosByDeveloperName().get(rtDeveloperName).getRecordTypeId();
	}

	private static Account createAccount(String name) {
		return new Account(
			Name = name
		);
	}

	private static DocumentAlyante__c createDocumentAlyante(String status, Id accountId, Id rtId) {
		return new DocumentAlyante__c(
			Status__c = status,
			Account__c = accountId,
			RecordTypeId = rtId
		);
	}

	private static List<TriggerSetting__mdt> createCustomMetadata(Boolean status) {
		List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
			'[' +
				'{' +
					'"DeveloperName": "Links",' +
					'"DocumentAlyanteAfterInsert__c": "' + status + '",' +
					'"DocumentAlyanteAfterUpdate__c": "' + status + '",' +
					'"DocumentAlyanteBeforeUpdate__c": "' + status + '"' +
				'}' +
			']'
			,List<TriggerSetting__mdt>.class
		);
		return triggerSettingMDT;
	}
}