force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/DocumentAlyante__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentAlyante__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>ToBeEmitted</fullName>
                <label>To Be Emitted</label>
            </value>
            <value>
                <fullName>Emitted</fullName>
            </value>
            <value>
                <fullName>ToBePayed</fullName>
                <label>To Be Payed</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>PaidPartly</fullName>
                <label>Paid Partly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentAlyante__c/recordTypes/ActiveInvoice.recordType-meta.xml
<RecordType>
    <fullName>ActiveInvoice</fullName>
    <active>true</active>
    <label>Active Invoice</label>
</RecordType>

force-app/main/default/objects/DocumentDetailAlyante__c/DocumentDetailAlyante__c.object-meta.xml
<CustomObject>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentDetailAlyante__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <referenceTo>DocumentAlyante__c</referenceTo>
    <relationshipLabel>Documents Details</relationshipLabel>
    <relationshipName>DocumentsDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentDetailAlyante__c/recordTypes/Final.recordType-meta.xml
<RecordType>
    <fullName>Final</fullName>
    <active>true</active>
    <label>Final</label>
</RecordType>

force-app/main/default/objects/TriggerSetting__mdt/TriggerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Manages the execution of the Apex Trigger</description>
    <label>Trigger Setting</label>
    <pluralLabel>Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerSetting__mdt/fields/DocumentDetailAlyanteBeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>DocumentDetailAlyanteBeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DocumentDetailAlyanteBeforeInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OnDocumentDetailAlyanteTest.cls
/**
 * @description       : 
 * @author            : §
 * @group             : 
 * @last modified on  : 01-20-2022
 * @last modified by  : §
**/
@isTest
public class OnDocumentDetailAlyanteTest {
    private static final Id ACTIVE_INVOICE_RT = getDocumentRecordTypeIdByDeveloperName('ActiveInvoice');
    @TestSetup static void makeData(){
        
        User testUser = createUser();
        insert testUser;
        
        Account testAccount = createAccount('Test Account');
        insert testAccount;
        
        DocumentAlyante__c invoice = createDocumentAlyante('Emitted', testAccount.Id, ACTIVE_INVOICE_RT);
        insert invoice;
    }
    
    private static DocumentDetailAlyante__c createDocument(){
        Id createDocumentDetailAlyante = [SELECT Id FROM DocumentAlyante__c LIMIT 1].Id;
        
        return new DocumentDetailAlyante__c(
            Document__c = createDocumentDetailAlyante
        );    
    }
    
    @isTest static void insertDocumentDetailTest() {
        User u = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
       
        TriggerUtilities.TriggerSettingDocumentDetailAlyante = createCustomMetadata(true);
        System.runAs(u) {
            Test.startTest();
            try {
                insert createDocument();
                System.assert(false);
            } catch(Exception e) {
                System.assert(true);
            }
            
            Test.stopTest();
        }
    }
    
    
    private static User createUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        String username = 'testuser@test' + Math.round(Math.random() * 10000) + '.com';
        
        return new User(
            Alias = 'standt',
            Email = username,
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = username
        );
    }
    
    private static Id getDocumentRecordTypeIdByDeveloperName(String rtDeveloperName) {
        return Schema.sObjectType.DocumentAlyante__c.getRecordTypeInfosByDeveloperName().get(rtDeveloperName).getRecordTypeId();
    }
    
    private static Account createAccount(String name) {
        return new Account(
            Name = name
        );
    }
    
    private static DocumentAlyante__c createDocumentAlyante(String status, Id accountId, Id rtId) {
        return new DocumentAlyante__c(
            Status__c = status,
            Account__c = accountId,
            RecordTypeId = rtId
        );
    }
    
    private static DocumentDetailAlyante__c createDocumentDetailAlyante(Id documentAlyanteId){
        return new DocumentDetailAlyante__c(
            Document__c = documentAlyanteId
        );
    }

    private static List<TriggerSetting__mdt> createCustomMetadata(Boolean status) {
		List<TriggerSetting__mdt> triggerSettingMDT = (List<TriggerSetting__mdt>) Json.deserialize(
			'[' +
				'{' +
					'"DeveloperName": "Links",' +
					'"DocumentDetailAlyanteBeforeInsert__c": "' + status + '"' +
				'}' +
			']'
			,List<TriggerSetting__mdt>.class
		); 
		return triggerSettingMDT;
	}
}