force-app/main/default/objects/OpportunitySetting__c/OpportunitySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Opportunity Setting</label>
</CustomObject>

force-app/main/default/objects/OpportunitySetting__c/fields/FteWhere__c.field-meta.xml
<CustomField>
    <fullName>FteWhere__c</fullName>
    <label>FteWhere</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Budget_gg__c.field-meta.xml
<CustomField>
    <fullName>Budget_gg__c</fullName>
    <label>Budget (gg)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Data_fine_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_fine_prevista__c</fullName>
    <label>Data fine prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Stima_gg_a_terminare__c.field-meta.xml
<CustomField>
    <fullName>Stima_gg_a_terminare__c</fullName>
    <label>Stima a terminare (gg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TriggerCustomSetting__c/TriggerCustomSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Manages the execution of the trigger</description>
    <label>Trigger Custom Setting</label>
</CustomObject>

force-app/main/default/objects/TriggerCustomSetting__c/fields/NexusProjectStatusAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>NexusProjectStatusAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nexus ProjectStatus After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerCustomSetting__c/fields/NexusProjectStatusAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>NexusProjectStatusAfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nexus ProjectStatus After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerCustomSetting__c/fields/NexusProjectStatusBeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>NexusProjectStatusBeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nexus ProjectStatus Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerCustomSetting__c/fields/NexusProjectStatusBeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>NexusProjectStatusBeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nexus ProjectStatus Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OnProjectStatusTest.cls
@isTest
public class OnProjectStatusTest {
    @testSetUp
    public static void testOnProjectStatus(){
        
        TriggerCustomSetting__c triggerCustomSetting = new TriggerCustomSetting__c();
        triggerCustomSetting.NexusProjectStatusAfterInsert__c = true;
        triggerCustomSetting.NexusProjectStatusAfterUpdate__c = true;
        triggerCustomSetting.NexusProjectStatusBeforeInsert__c = true;
        triggerCustomSetting.NexusProjectStatusBeforeUpdate__c = true;

        OpportunitySetting__c sett = new OpportunitySetting__c(
           FteWhere__c = 'Name = \'testName\''
        );
        insert sett;
           
        Account account = new Account(
            name= 'TestName');
        insert account;
        
        Opportunity opportunity = new Opportunity(
            AccountId = account.id,
            Name = 'oppTest',
            StageName = 'Prospecting',
            CloseDate = Date.today());
        insert opportunity;
        
        Project_Status__c ProjectStatus = new Project_Status__c(
            name = 'testName',
            Budget_gg__c = 10000,
            Data_fine_prevista__c = Date.today()+30,
            Stima_gg_a_terminare__c = 5,
            Opportunity__c = opportunity.Id);
        insert ProjectStatus;
    }
    
    
    @istest
    public static void testOnProjectStatusSchedulable(){
        OnProjectStatusSchedulable ops = new OnProjectStatusSchedulable();
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        System.schedule('test', CRON_EXP, ops);
        
    }
    
}