force-app/main/default/objects/Opportunity/fields/Delivery_Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>NexusAT</value>
        </filterItems>
        <filterItems>
            <field>Contact.Roles__c</field>
            <operation>equals</operation>
            <value>Project Manager</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Budget_gg__c.field-meta.xml
<CustomField>
    <fullName>Budget_gg__c</fullName>
    <label>Budget (gg)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>NexusAT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Budget_gg__c.field-meta.xml
<CustomField>
    <fullName>Budget_gg__c</fullName>
    <inlineHelpText>Totale giorni/uomo.</inlineHelpText>
    <label>Budget (gg)</label>
    <summarizedField>QuoteLineItem.Quantity</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CreateProjectStatus.cls
/*
 * LastModification
 * @author	¤
 * @date	16/11/2020
 * @see		CreateProjectStatusTest.apxc
 * @description
 *      Nel metodo createProjectStatus(Opportunity opp), i campi ReferenceNumber__c e Account__c
 *      verranno allineati con corrispettivi campi presenti nell'opportunity padre
 */
public class CreateProjectStatus {
    private static Map<Id, Quote> quoteMap = New Map<Id, Quote>();
    //Called from Proces Builder
    @InvocableMethod
    public static void createProjectStatusInvocable(List<Id> listOppIds){
        List<Project_Status__c> listProjectStatus = New List<Project_Status__c>();
        List<Opportunity> oppList = [SELECT Id, Name, SyncedQuoteId, Delivery_Project_Manager__c, Reference_Number__c, AccountId
                                    FROM Opportunity
                                    WHERE Id In : listOppIds];

        Map<Id, Opportunity> oppMap = New Map<Id, Opportunity>(oppList);
        quoteMap = New Map<Id, Quote>([SELECT Id, Status, Budget_gg__c FROM Quote WHERE Id in : getQuoteIdList(oppList)] );

        for(Opportunity opp : oppMap.values()){            
            //Check SyncedQuoteId != ''
            System.debug('Id +'+ opp.SyncedQuoteId);
            if(opp.SyncedQuoteId != null){
                if(quoteMap.get(opp.SyncedQuoteId).Status == 'Accepted'){
                    //call method that create project status
                    Project_Status__c ps = createProjectStatus(opp);
                    listProjectStatus.add(ps);
                }
            }
        }
        if(!listProjectStatus.isEmpty()){
            System.debug(listProjectStatus);
            insert listProjectStatus;
        }
    }
    //Create Project Status
    public static Project_Status__c createProjectStatus(Opportunity opp){
        //get the Opportunity Name without NX-0000
        //String psName = '';
        //psName = opp.Name.substring(9);

        Project_Status__c newProjectStatus = New Project_Status__c();
        //newProjectStatus.Name = 'Project - ' + psName;
        newProjectStatus.Name = 'Project - ' + opp.Name;
        newProjectStatus.Pm__c = opp.Delivery_Project_Manager__c;
        newProjectStatus.Opportunity__c = opp.Id;
        newProjectStatus.Budget_gg__c = quoteMap.get(opp.SyncedQuoteId).Budget_gg__c;
        newProjectStatus.ReferenceNumber__c = opp.Reference_Number__c;
        newProjectStatus.Account__c = opp.AccountId;

        return newProjectStatus;
    }
    //getQuoteIdList
    public static List<Id> getQuoteIdList(List<Opportunity> oppList){
        List<Id> quoteListId = New List<Id>();

        for(Opportunity opp : oppList){
            quoteListId.add(opp.SyncedQuoteId);
        }
        return quoteListId;
    }
}