force-app/main/default/objects/Opportunity/fields/GapIndicator__c.field-meta.xml
<CustomField>
    <fullName>GapIndicator__c</fullName>
    <description>Graphic indicator of turnover to plan (Green if the gap is 0, Yellow if there are missing invoices, Red if there are excess invoices)</description>
    <formula>IMAGE( 
	IF(  RevenueToPlan__c &gt; 0 , 
		&quot;/resource/red&quot;,  
			IF( RevenueToPlan__c &lt; 0 , 
				&quot;/resource/yellow&quot;,  
					IF( RevenueToPlan__c = 0, 
						&quot;/resource/green&quot;, &quot;&quot;) ) ) , 
&apos;Indicator&apos; , 20, 20)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Green: regular situation.
Yellow: excess invoices.
Red: missing invoices.</inlineHelpText>
    <label>Gap Indicator</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RevenueToPlan__c.field-meta.xml
<CustomField>
    <fullName>RevenueToPlan__c</fullName>
    <formula>Amount - (TotalSettled__c + TotalSentInvoices__c +  TotalInDraft__c +  TotalToBeInvoiced__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Gap between the amount of the Opportunity and the total amount of the linked Invoice Milestones</inlineHelpText>
    <label>Revenue To Plan</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalInDraft__c.field-meta.xml
<CustomField>
    <fullName>TotalInDraft__c</fullName>
    <description>Amount of Invoice Milestone in draft</description>
    <label>Total In Draft</label>
    <summarizedField>InvoiceMilestone__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceMilestone__c.Stage__c</field>
        <operation>equals</operation>
        <value>Draft</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceMilestone__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSentInvoices__c.field-meta.xml
<CustomField>
    <fullName>TotalSentInvoices__c</fullName>
    <description>Invoice Milestone amount on sent invoice</description>
    <label>Total Sent Invoices</label>
    <summarizedField>InvoiceMilestone__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceMilestone__c.Stage__c</field>
        <operation>equals</operation>
        <value>Fattura Inviata</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceMilestone__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSettled__c.field-meta.xml
<CustomField>
    <fullName>TotalSettled__c</fullName>
    <description>Amount of invoice milestones paid</description>
    <label>Total Settled</label>
    <summarizedField>InvoiceMilestone__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceMilestone__c.Stage__c</field>
        <operation>equals</operation>
        <value>Fattura Pagata</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceMilestone__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSettledPercentage__c.field-meta.xml
<CustomField>
    <fullName>TotalSettledPercentage__c</fullName>
    <description>Amount of invoice milestones paid as a percentage</description>
    <formula>(TotalSettled__c  / Amount) * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Settled (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalToBeInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalToBeInvoiced__c</fullName>
    <description>Amount of Invoice Milestone to be invoiced</description>
    <label>Total To Be Invoiced</label>
    <summarizedField>InvoiceMilestone__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InvoiceMilestone__c.Stage__c</field>
        <operation>equals</operation>
        <value>Da Fatturare</value>
    </summaryFilterItems>
    <summaryForeignKey>InvoiceMilestone__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ProgressBarController.cls
/**
 * @description       : 
 * @author            : 
 * @last modified on  : 25/01/2021
 * @last modified by  : ¤ → alessio.marra@nexusat.it
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0                                               Initial Version
 * 1.1   25/01/2021   ¤ → alessio.marra@nexusat.it   Review ApiName Nomenclature
**/
public class ProgressBarController {
	@AuraEnabled
	public static Opportunity getOppFields(Id recordId){
		system.debug('Ø-recordId ' + recordId);
		Opportunity opp = [SELECT Id, Amount,TotalInDraft__c,TotalSentInvoices__c,TotalSettled__c,
							RevenueToPlan__c,TotalToBeInvoiced__c,TotalSettledPercentage__c,GapIndicator__c
							FROM Opportunity
							WHERE Id =: recordId];
		return opp;
	}
}