force-app/main/default/objects/Contact/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FattureInCloudSettings__c/FattureInCloudSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Informazioni per accesso a Fatture in Cloud via REST API.</description>
    <label>Fatture In Cloud Settings</label>
</CustomObject>

force-app/main/default/objects/FattureInCloudSettings__c/fields/AdministrationEmail__c.field-meta.xml
<CustomField>
    <fullName>AdministrationEmail__c</fullName>
    <label>Administration Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/InvoiceExternalCode__c.field-meta.xml
<CustomField>
    <fullName>InvoiceExternalCode__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the invoice code present on the company billing system</inlineHelpText>
    <label>Invoice External Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BillingOpportunity__c.field-meta.xml
<CustomField>
    <fullName>BillingOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Opportunity.Invoicing__c</field>
            <operation>notEqual</operation>
            <value>N/A</value>
        </filterItems>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>Opportunity.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BusinessManager__c.field-meta.xml
<CustomField>
    <fullName>BusinessManager__c</fullName>
    <label>Business Manager</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flavia Dall&apos;Ora</fullName>
            </value>
            <value>
                <fullName>Francesco Veropalumbo</fullName>
            </value>
            <value>
                <fullName>Fulvio Vanacore</fullName>
            </value>
            <value>
                <fullName>Giovanni Costagliola</fullName>
            </value>
            <value>
                <fullName>Giuseppe Maiorano</fullName>
            </value>
            <value>
                <fullName>Massimo Colombo</fullName>
            </value>
            <value>
                <fullName>Roberto De Simone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DeliveryProjectManager__c.field-meta.xml
<CustomField>
    <fullName>DeliveryProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GrossMargin__c.field-meta.xml
<CustomField>
    <fullName>GrossMargin__c</fullName>
    <formula>TradingProfit__c / Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Invoicing__c</fullName>
    <label>Invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipi_di_Fatturazioni</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Type</label>
    <referenceTo>PaymentType__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>PRJ</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
                <label>Salesforce</label>
            </value>
            <value>
                <fullName>Operation</fullName>
            </value>
            <value>
                <fullName>Digital Marketing</fullName>
            </value>
            <value>
                <fullName>Altro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TradingProfit__c.field-meta.xml
<CustomField>
    <fullName>TradingProfit__c</fullName>
    <formula>Amount - TotalInternalCostSynced__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trading Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PaymentType__c/PaymentType__c.object-meta.xml
<CustomObject>
    <label>Payment Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/BudgetDD__c.field-meta.xml
<CustomField>
    <fullName>BudgetDD__c</fullName>
    <inlineHelpText>Total days/man</inlineHelpText>
    <label>Budget (dd)</label>
    <summarizedField>QuoteLineItem.Quantity</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalInternalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalInternalCost__c</fullName>
    <description>Total internal cost, obtained from the single internal costs of the Quote Line Items</description>
    <label>Total Internal Cost</label>
    <summarizedField>QuoteLineItem.TotalInternalCost__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TotalInternalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalInternalCost__c</fullName>
    <formula>Quantity  *  InternalCost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Internal Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SetAddressSetting__c/SetAddressSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Email addresses to send emails</description>
    <label>Set Address Setting</label>
</CustomObject>

force-app/main/default/objects/SetAddressSetting__c/fields/EmailCDG__c.field-meta.xml
<CustomField>
    <fullName>EmailCDG__c</fullName>
    <label>Email CDG</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SetAddressSetting__c/fields/OtherAddress__c.field-meta.xml
<CustomField>
    <fullName>OtherAddress__c</fullName>
    <label>Other Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/globalValueSets/Tipi_di_Fatturazioni.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Canone Quadrimestrale</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Semestrale</fullName>
    </customValue>
    <customValue>
        <fullName>Canone Trimestrale</fullName>
    </customValue>
    <customValue>
        <fullName>Fee Mensile</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (#Ticket)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (0-0-100 =Equivale a 100%consegna finale)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (100-0-0 =Equivale a 100%ordine)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (30-40-30)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (30-50-20 =Equivale a 30%ordine, 50%UAT, 20%consegnafinale)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (40-30-30)</fullName>
    </customValue>
    <customValue>
        <fullName>SAL (50-50)</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Tipi di Fatturazioni</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendEmailClass.cls
/**
 * @description       : 
 * @author            : 
 * @last modified on  : 25/01/2021
 * @last modified by  : ¤ → alessio.marra@nexusat.it
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0                                               Initial Version
 * 1.1   25/01/2021   ¤ → alessio.marra@nexusat.it   Review ApiName Nomenclature
**/
public class SendEmailClass {
	
	//CSS for mail formatting
	public static String tableStyle = 'margin-bottom : 10px;';
	public static String thStyle = 'text-align:left; white-space: nowrap; border-bottom:1px solid #FE7D19; color:#000;color:#fe7d19;font-weight:bold;padding:0px 8px;font-size:0.8em';
	public static String thStyle2 = 'margin-top:30px; text-align:left; white-space: nowrap; border-bottom:1px solid #FE7D19; color:#000;color:#fe7d19;font-weight:bold;padding:0px 8px;font-size:0.8em';
	public static String valueStyleNew = 'min-height:16px;padding:8px;background:#eee';
	public static String valueStyleNew2 = 'min-height:16px;padding:8px;background:#fff';
	
	//Set Email Body
	public static void sendEmailVerifica(List<String> accountToUpdate, String subject, String body){
		
		//Get Email Address to send from Custom Setting
		FattureInCloudSettings__c fattSettings = FattureInCloudSettings__c.getOrgDefaults();
		String emailRef = fattSettings.AdministrationEmail__c;
		List<String> destinationAddress = New List<String>();
		destinationAddress.add(emailRef);
		
		//Create subject and body for email
		String bodyTest = body +': <ul>';
		
		for(String s : accountToUpdate){
			bodyTest += '<li>' + s + '</li>';
		}
		bodyTest += '</ul>';
		
		//Send Email Message       
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		mail.setToAddresses(destinationAddress);
		mail.setSubject(subject);
		mail.setHtmlBody(bodyTest);
		Messaging.SendEmailResult[] result = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
	}
	
	//Get Opportunity Field 
	@AuraEnabled
	public static Opportunity getOppField(Id recordId){
		system.debug('Ø-recordId ' + recordId);
		Opportunity opp = [SELECT Id, Name, Amount,StageName,CloseDate
						   FROM Opportunity
						   WHERE Id =: recordId];  
		return opp;
	}
	//Called from Proces Builder
	@InvocableMethod
	public static void sendEmailInvocable(List<Id> listOppIds){
		
		for(Id oppId : listOppIds){
			sendEmail(oppId);
		}
	}
	//Send Email
	@AuraEnabled
	public static Boolean sendEmail(Id recordId){
		system.debug('Ø-recordId ' + recordId);
		Boolean check = false;
		
		try{
			String head = '';
			String body = '';
			String headQLI = '';
			String bodyQLI = '';
			String oppReferenceNumber= '';
			String oppTable = '';
			
			//Get User Current User Email
			// User currentUser = [select id, title, firstname, lastname, email, phone, mobilephone, fax, street, city, state, postalcode, country
			//                     FROM User WHERE id =: UserInfo.getUserId()];
			// String emailRef = currentUser.Email ;
			
			//Create List of Destination Address
			List<String> DestinationAddress = New List<String>();
			
			//Get Email Address From Custom Setting
			SetAddressSetting__c address = SetAddressSetting__c.getOrgDefaults();
			DestinationAddress.add(address.EmailCDG__c);
			DestinationAddress.add(address.OtherAddress__c);
			System.debug('Ø-DestinationAddress '+DestinationAddress);
			
			//Select Opportunity and Contact Field
			Opportunity opp = [SELECT Id,AccountId, Name, ReferenceNumber__c, StageName, SyncedQuoteId
							   FROM Opportunity 
							   WHERE Id =: recordId];

			List<Messaging.SingleEmailMessage> emailNew = New List<Messaging.SingleEmailMessage>();
			Messaging.SingleEmailMessage email = New Messaging.SingleEmailMessage();
			email.setToAddresses(DestinationAddress);
			email.setSubject('Opportunità '+opp.Name +' in Stato '+opp.StageName);
			email.setWhatId(recordId);            
			email.setTreatTargetObjectAsRecipient(false);
			
			//Get All Id of Content Document Link of Opportunity and create a final list of Id of Content Document to Send
			List<ContentDocumentLink> conDocLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId, SystemModstamp 
														FROM ContentDocumentLink 
														where LinkedEntityId =: recordId
													   ];

			List<Id> contentdocumentId = New List<Id>();
			List<Id> contentdocumentIdToSend = New List<Id>();
			oppReferenceNumber = opp.ReferenceNumber__c;

			for(ContentDocumentLink cdl : conDocLinkList){
				contentdocumentId.add(cdl.ContentDocumentId);
			}
			
			List<ContentDocument> cdList = [SELECT Id, Title, FileExtension 
											FROM ContentDocument 
											WHERE Id IN :contentdocumentId];

			for(ContentDocument cd : cdList){
				String cdTitle = cd.Title;
				String cdFE = cd.FileExtension;
				if(cdTitle.startsWith(oppReferenceNumber) && (cdFE == 'pdf' || cdFE == 'docx' || cdFE == 'xlsx')){
					System.debug('cycle cdTitle---'+ cdTitle +'   cdfe'+cdFE);
					contentdocumentIdToSend.add(cd.Id);
				}
			}
			List<ContentVersion> cvList = [SELECT Id, IsLatest, ContentDocumentId, Title, FileType, VersionData,FileExtension 
										   FROM ContentVersion 
										   WHERE ContentDocumentId IN :contentdocumentIdToSend ];
			
			List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
			
			for(ContentVersion cv : cvList){
				Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
				efa.setFileName(cv.Title+'.'+cv.FileExtension);
				efa.setBody(cv.VersionData);
				fileAttachments.add(efa);                
			}
			email.setFileAttachments(fileAttachments);
			body = EmailBody(recordId);
			if(opp.StageName == 'Closed Won'){
				if(opp.SyncedQuoteId != null){
					bodyQLI = emailBodyQli(opp);
					if(bodyQLI.length()>0){
						Quote q = [SELECT Id, Name, OpportunityId,Pricebook2.Name,BudgetDD__c FROM Quote WHERE Id =: opp.SyncedQuoteId];
						//Compose Email's Head 
						headQLI = '<p>Riepilogo Budget: <ul><li>Budget (gg): '+q.BudgetDD__c +';</li><li>PriceBook: '+q.Pricebook2.Name +';</li></ul></p><table cellspacing="0" cellpadding="0" border="0" style="'+tableStyle+'"><thead><th style="'+thStyle2+'">Risorsa</th><th style="'+thStyle2+'">Quantità</th><th style="'+thStyle2+'">Costo Totale Interno</th><th style="'+thStyle2+'">Prezzo di Vendita Totale</th></thead><tbody>';   
					}
				}
			}
			if(body.length()>0){
				//Compose Email's Head 
				head = '<table cellspacing="0" cellpadding="0" border="0" style="'+tableStyle+'"><thead><th style="'+thStyle+'">Invoice Milestone Name </th><th style="'+thStyle+'">Descrizione</th><th style="'+thStyle+'">Stato</th><th style="'+thStyle+'">Imponibile</th><th style="'+thStyle+'">Data Prevista</th></thead><tbody>';   
			}
			
			oppTable = OppBody(recordId);
			email.setHtmlBody(oppTable + head + body + headQLI +bodyQLI);
			emailNew.add(email);
			Messaging.SendEmailResult [] r = Messaging.sendEmail(emailNew,false); 
			System.debug('Ø-r '+r);
			check = true;
			
		}catch (Exception ex){
			System.Debug('ex*********'+ex);
			throw new AuraHandledException('Inserire almeno un allegato. '+ex.getMessage());
		}
		return check;
	}
	//Send Email Fulvio
	@AuraEnabled
	public static Boolean sendEmailAllStates(Id recordId, List<String> DestinationAddress){
		system.debug('Ø-recordId ' + recordId);
		Boolean check = false;
		
		try{
			String head = '';
			String body = '';
			String headQLI = '';
			String bodyQLI = '';
			String oppReferenceNumber= '';
			String oppTable = '';
						
			//Select Opportunity and Contact Field
			Opportunity opp = [SELECT Id,AccountId, Name, ReferenceNumber__c, StageName, SyncedQuoteId
							   FROM Opportunity 
							   WHERE Id =: recordId];

			List<Messaging.SingleEmailMessage> emailNew = New List<Messaging.SingleEmailMessage>();
			Messaging.SingleEmailMessage email = New Messaging.SingleEmailMessage();
			email.setToAddresses(DestinationAddress);
			email.setSubject('Opportunità '+opp.Name +' in Stato '+opp.StageName);
			email.setWhatId(recordId);            
			email.setTreatTargetObjectAsRecipient(false);
			
			//Get All Id of Content Document Link of Opportunity and create a final list of Id of Content Document to Send
			List<ContentDocumentLink> conDocLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId, SystemModstamp 
														FROM ContentDocumentLink 
														where LinkedEntityId =: recordId
													   ];

			List<Id> contentdocumentId = New List<Id>();
			List<Id> contentdocumentIdToSend = New List<Id>();
			oppReferenceNumber = opp.ReferenceNumber__c;

			for(ContentDocumentLink cdl : conDocLinkList){
				contentdocumentId.add(cdl.ContentDocumentId);
			}
			
			List<ContentDocument> cdList = [SELECT Id, Title, FileExtension 
											FROM ContentDocument 
											WHERE Id IN :contentdocumentId];

			for(ContentDocument cd : cdList){
				String cdTitle = cd.Title;
				String cdFE = cd.FileExtension;
				if(cdTitle.startsWith(oppReferenceNumber) && (cdFE == 'pdf' || cdFE == 'docx' || cdFE == 'xlsx')){
					System.debug('cycle cdTitle---'+ cdTitle +'   cdfe'+cdFE);
					contentdocumentIdToSend.add(cd.Id);
				}
			}
			List<ContentVersion> cvList = [SELECT Id, IsLatest, ContentDocumentId, Title, FileType, VersionData,FileExtension 
										   FROM ContentVersion 
										   WHERE ContentDocumentId IN :contentdocumentIdToSend ];
			
			List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
			
			for(ContentVersion cv : cvList){
				Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
				efa.setFileName(cv.Title+'.'+cv.FileExtension);
				efa.setBody(cv.VersionData);
				fileAttachments.add(efa);                
			}
			email.setFileAttachments(fileAttachments);
			body = EmailBody(recordId);
			if(opp.StageName == 'Closed Won'){
				if(opp.SyncedQuoteId != null){
					bodyQLI = emailBodyQli(opp);
					if(bodyQLI.length()>0){
						Quote q = [SELECT Id, Name, OpportunityId,Pricebook2.Name,BudgetDD__c FROM Quote WHERE Id =: opp.SyncedQuoteId];
						//Compose Email's Head 
						headQLI = '<p>Riepilogo Budget: <ul><li>Budget (gg): '+q.BudgetDD__c +';</li><li>PriceBook: '+q.Pricebook2.Name +';</li></ul></p><table cellspacing="0" cellpadding="0" border="0" style="'+tableStyle+'"><thead><th style="'+thStyle2+'">Risorsa</th><th style="'+thStyle2+'">Quantità</th><th style="'+thStyle2+'">Costo Totale Interno</th><th style="'+thStyle2+'">Prezzo di Vendita Totale</th></thead><tbody>';   
					}
				}
			}
			if(body.length()>0){
				//Compose Email's Head 
				head = '<table cellspacing="0" cellpadding="0" border="0" style="'+tableStyle+'"><thead><th style="'+thStyle+'">Invoice Milestone Name </th><th style="'+thStyle+'">Descrizione</th><th style="'+thStyle+'">Stato</th><th style="'+thStyle+'">Imponibile</th><th style="'+thStyle+'">Data Prevista</th></thead><tbody>';   
			}
			
			oppTable = OppBody(recordId);
			email.setHtmlBody(oppTable + head + body + headQLI +bodyQLI);
			emailNew.add(email);
			Messaging.SendEmailResult [] r = Messaging.sendEmail(emailNew,false); 
			System.debug('Ø-r '+r);
			check = true;
			
		}catch (Exception ex){
			System.Debug('ex*********'+ex);
			throw new AuraHandledException('Inserire almeno un allegato. '+ex.getMessage());
		}
		return check;
	}
	
	//Set Milestone Information
	@AuraEnabled
	public static String EmailBody(Id recordId){
		String body = '';
		String imAccountName = '';
		Double imAmmontare = 0;
		String imDescription = '';
		Integer i = 1;
		
		List<InvoiceMilestone__c> imList = [SELECT Id,Name,AccountName__c,Amount__c,Description__c,ExpectedDate__c,Opportunity__r.Name,Stage__c,InvoiceExternalCode__c
											 FROM InvoiceMilestone__c
											 WHERE Opportunity__c =:recordId];
		if(!imList.isEmpty()){
			for(InvoiceMilestone__c im : imList){
				if(math.mod(i, 2) == 0 ){
					body += '<tr class="even"><td><div style="'+valueStyleNew +'">'+im.Name+'</div></td><td><div style="'+valueStyleNew +'">'+im.Description__c+'</div></td><td><div style="'+valueStyleNew +'">'+im.Stage__c+'</div></td><td><div style="'+valueStyleNew +'">€ '+im.Amount__c+'</div></td><td><div style="'+valueStyleNew +'">'+im.ExpectedDate__c.format()+'</div></td></tr>';
				}else{                
					body += '<tr class="odd"><td><div style="'+valueStyleNew2 +'">'+im.Name+'</div></td><td><div style="'+valueStyleNew2 +'">'+im.Description__c+'</div></td><td><div style="'+valueStyleNew2 +'">'+im.Stage__c+'</div></td><td><div style="'+valueStyleNew2 +'">€ '+im.Amount__c+'</div></td><td><div style="'+valueStyleNew2 +'">'+im.ExpectedDate__c.format()+'</div></td></tr>';
				}
				i++;
			}
			body += '</tbody></table>';
		}
		return body;
	}

	public static String emailBodyQli(Opportunity opp){
		String body = '';
		Integer i = 1;
		Quote q = [SELECT Id, Name, OpportunityId,Pricebook2.Name,BudgetDD__c FROM Quote WHERE Id =: opp.SyncedQuoteId];
		
		List<QuoteLineItem> qliList = [SELECT Id, Product2.Name, Quantity, UnitPrice, TotalPrice,TotalInternalCost__c FROM QuoteLineItem WHERE QuoteId =: q.Id];

		  if(!qliList.isEmpty()){
			for(QuoteLineItem qli : qliList){
				if(math.mod(i, 2) == 0 ){
					body += '<tr class="even"><td><div style="'+valueStyleNew +'">'+qli.Product2.Name+'</div></td><td><div style="'+valueStyleNew +'">'+qli.Quantity+'</div></td><td><div style="'+valueStyleNew +'">€ '+qli.TotalInternalCost__c+'</div></td><td><div style="'+valueStyleNew +'">€ '+qli.TotalPrice+'</div></td></tr>';
				}else{                
					body += '<tr class="odd"><td><div style="'+valueStyleNew2 +'">'+qli.Product2.Name+'</div></td><td><div style="'+valueStyleNew2 +'">'+qli.Quantity+'</div></td><td><div style="'+valueStyleNew2 +'">€ '+qli.TotalInternalCost__c+'</div></td><td><div style="'+valueStyleNew2 +'">€ '+qli.TotalPrice+'</div></td></tr>';
				}
				i++;
			}
			body += '</tbody></table>';
		}
		return body;
	}
	
	//Set Opportunity Information
	@AuraEnabled
	public static String OppBody(Id recordId){
		String text = '';
		String serType = '';
		String delMan = '';
		String tipPaga = '';
		String oppfatt = '';
		String tp = '';
		String recOwn = '';
		Double traPro = 0.0;
		Double grosMar = 0.0;

		Opportunity opp = [SELECT Id, Account.Name, Name, Amount, StageName, CloseDate, ReferenceNumber__c, ServiceType__c,
							DeliveryProjectManager__r.Name, PaymentType__r.Name, Invoicing__c, Type, BusinessManager__c,TradingProfit__c, GrossMargin__c, BillingOpportunity__r.Name
						   FROM Opportunity 
						   WHERE Id =: recordId];
		String dataPrevista = opp.CloseDate.format();
		serType = (opp.ServiceType__c <> null)? opp.ServiceType__c :'N.A.';
		delMan = (opp.DeliveryProjectManager__r <> null)? opp.DeliveryProjectManager__r.Name :'N.A.';
		tipPaga = (opp.PaymentType__r.Name <> null)? opp.PaymentType__r.Name :'N.A.';
		oppfatt = (opp.BillingOpportunity__r.Name <> null)? opp.BillingOpportunity__r.Name :'N.A.';
		tp = (opp.Type <> null)? opp.Type :'N.A.';
		recOwn = (opp.BusinessManager__c <> null)? opp.BusinessManager__c :'N.A.';
		traPro = (opp.TradingProfit__c <> null)? opp.TradingProfit__c : 0.0;
		grosMar = (opp.GrossMargin__c <> null)? opp.GrossMargin__c : 0.0;

		text = '<div><p>Gentile Amministrazione NexusAT,</p> <p> l\'Opportunità N° '+ opp.Name+' è in Stato di '+opp.StageName;
		text += '<p>Di seguito le informazioni principali: </p><ul><li>Nome Account : '+opp.Account.Name +'</li><li>Imponibile: € '+opp.Amount +'</li><li>Stato: '+opp.StageName +'</li><li>Data Prevista: '+ dataPrevista +'</li>';
		text += '<li>Reference Number: '+opp.ReferenceNumber__c +'</li>';
		text += '<li>Service Type: '+serType +'</li>';
		text += '<li>Delivery Project Manager: '+ delMan+'</li>';
		text += '<li>Tipo Pagamento: '+ tipPaga +'</li>';
		text += '<li>Account Jira di Riferimento: '+oppfatt +'</li>';
		text += '<li>Type: '+ tp+'</li>';
		text += '<li>Business Manager: '+recOwn +'</li>';
		text += '<li>Trading Profit: € '+traPro +'</li>';
		text += '<li>Gross Margin: '+ grosMar +' %</li>';
		text += '</ul><p>Il piano di fatturazione è:</p></div>';
		return text;
	}
}