force-app/main/default/objects/Cost__c/Cost__c.object-meta.xml
<CustomObject>
    <label>Cost</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Costs</relationshipLabel>
    <relationshipName>Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cost__c/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost__c/fields/TotalCostValue__c.field-meta.xml
<CustomField>
    <fullName>TotalCostValue__c</fullName>
    <formula>Cost_Value__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CostHRMargin__c.field-meta.xml
<CustomField>
    <fullName>CostHRMargin__c</fullName>
    <label>Cost HR Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CostMargin__c.field-meta.xml
<CustomField>
    <fullName>CostMargin__c</fullName>
    <label>Cost Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsMarginValid__c.field-meta.xml
<CustomField>
    <fullName>IsMarginValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Margin Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/isMinMarginValid__c.field-meta.xml
<CustomField>
    <fullName>isMinMarginValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Min Margin Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/Quote_Revenue__c.object-meta.xml
<CustomObject>
    <label>Quote Revenue</label>
    <nameField>
        <displayFormat>QRN-{000000}</displayFormat>
        <label>Quote Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Revenues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Revenue__c/fields/LinksRevenue__c.field-meta.xml
<CustomField>
    <fullName>LinksRevenue__c</fullName>
    <label>Links Revenue (€)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/QuotaATI__c.field-meta.xml
<CustomField>
    <fullName>QuotaATI__c</fullName>
    <label>Quota ATI (€)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Revenue__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Revenues</relationshipLabel>
    <relationshipName>Quote_Revenues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Revenue_Type__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Type__c</fullName>
    <label>Revenue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Revenue_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TotalCost__c.field-meta.xml
<CustomField>
    <fullName>TotalCost__c</fullName>
    <formula>OvernightAllowanceCost__c +  TravelAllowanceCost__c +   DDTotalCost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RevenueTypesCS__c/RevenueTypesCS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Revenue Types CS</label>
</CustomObject>

force-app/main/default/objects/RevenueTypesCS__c/fields/DefaultMargin__c.field-meta.xml
<CustomField>
    <fullName>DefaultMargin__c</fullName>
    <label>Default Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RevenueTypesCS__c/fields/MinMargin__c.field-meta.xml
<CustomField>
    <fullName>MinMargin__c</fullName>
    <label>Min Margin (%)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Revenue_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Prestazioni di Servizi</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Vendita Hardware</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Vendita Software e Servizi</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Prestazioni di servizi c/terzi T&amp;M</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Vendita di asset</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Canoni per prestazioni</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Altri ricavi</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>Rivendita prodotti finiti HW/SW</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Servizi</fullName>
        <isActive>false</isActive>
        <label>Acquisto Servizi</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Hardware</fullName>
        <isActive>false</isActive>
        <label>Acquisto Hardware</label>
    </customValue>
    <customValue>
        <fullName>Acquisto Software</fullName>
        <isActive>false</isActive>
        <label>Acquisto Software</label>
    </customValue>
    <customValue>
        <fullName>Trasferte</fullName>
        <isActive>false</isActive>
        <label>Trasferte</label>
    </customValue>
    <customValue>
        <fullName>Altri Costi Diretti</fullName>
        <isActive>false</isActive>
        <label>Altri Costi Diretti</label>
    </customValue>
    <customValue>
        <fullName>Prestazione Servizi</fullName>
        <isActive>false</isActive>
        <label>Prestazione Servizi</label>
    </customValue>
    <customValue>
        <fullName>Risorse Umane</fullName>
        <isActive>false</isActive>
        <label>Risorse Umane</label>
    </customValue>
    <customValue>
        <fullName>Utenze</fullName>
        <isActive>false</isActive>
        <label>Utenze</label>
    </customValue>
    <customValue>
        <fullName>Canoni</fullName>
        <isActive>false</isActive>
        <label>Canoni</label>
    </customValue>
    <customValue>
        <fullName>Contributo</fullName>
        <isActive>false</isActive>
        <label>Contributo</label>
    </customValue>
    <customValue>
        <fullName>Ammortamenti</fullName>
        <isActive>false</isActive>
        <label>Ammortamenti</label>
    </customValue>
    <customValue>
        <fullName>Spese varie</fullName>
        <isActive>false</isActive>
        <label>Spese varie</label>
    </customValue>
    <masterLabel>Revenue Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EconomicPlanController.cls
/**
 * @description       : Apex Controller for LWC economicPlanTableComponent 
 * @author            : Œ | Mirco Centrone
 * @last modified on  : 19-07-2021
 * @last modified by  : Œ
 * Modifications Log 
 * Ver   Date         Author   Modification
 * 0.5.1   01-04-2021   Œ   Initial Version
 * 0.6.0   26-04-2021   Œ   Modifiche all'algoritmo di approvazione e calcolo dell'economicPlan, richieste dal cliente.
 * 0.6.1   07-07-2021   Œ   Aggiunti campi in Update nel metodo setQuoteIsMarginValid che ritornano dal Javascript.
**/

public without sharing class EconomicPlanController {

    public without sharing class EconomicPlan{
        @AuraEnabled public String revenueType{get;set;}
        @AuraEnabled public Double costHR{get;set;}
        @AuraEnabled public Double cost{get;set;}
        @AuraEnabled public Double linksRevenue{get;set;}
        @AuraEnabled public Double ATI{get;set;}
        @AuraEnabled public Double totalRevenue;
        @AuraEnabled public Double defaultMarginPercent{get;set;}
        @AuraEnabled public Double minMarginPercent{get;set;}
        @AuraEnabled public Double minMargin{get;set;}
        @AuraEnabled public Double margin{get;set;}
        @AuraEnabled public Double profit;
        @AuraEnabled public Boolean marginCheck{get;set;}
        @AuraEnabled public Boolean rowError{get;set;}

        public void setMarginProfit(){
            this.margin = this.linksRevenue - this.costHR - this.cost;
            if(this.linksRevenue!=0){
                this.profit = ((this.linksRevenue - this.costHR - this.cost)/ (this.linksRevenue));
            }else{
                this.profit = 0;
            }
        }
        public Double getProfit(){
            return this.profit;
        }

        public void setMarginCheck(){
            this.marginCheck = this.profit >= this.defaultMarginPercent ? true : false; 
        }  
        public Boolean getMarginCheck(){
            return this.marginCheck;
        }

        public void setMinMargin(){
            this.minMargin = this.linksRevenue * this.minMarginPercent ;
        } 
        public Double getMinMargin(){
            return this.minMargin;
        }

        public void setTotalRevenue(){
            this.totalRevenue = this.linksRevenue + this.ATI;
        }
        public Double getTotalRevenue(){
            return this.totalRevenue;
        } 
    }

     /**
    * @description  : Wrapper for the Javascript callback.
    * @author Œ | 01-04-2021 
    **/
    @TestVisible
    private class CustomWrapper{
        @AuraEnabled
        public Id quoteId { get; set; }
        @AuraEnabled
        public Boolean marginCheck{ get; set; }
        @AuraEnabled
        public Boolean totalMarginCheck{ get; set; }
        @AuraEnabled
        public Integer costHRMargin{ get; set;}
        @AuraEnabled
        public Integer costMargin{ get; set;}
    } 

    /**
    * @description  : Get Economic Plan fields from Quote's related objects and calculate if profit margin is valid for each Revenue Type.
    * @author Œ | 01-04-2021 
    * @param id quoteID 
    * @return List<EconomicPlan>
    **/
    @AuraEnabled(cacheable=true)
    public static List<EconomicPlan> getEconomicPlan(id quoteID){
        System.debug('Œ EconomicPlanController.getEconomicPlan{ ');

        List<EconomicPlan> econPlanList = new List<EconomicPlan>();
        Map<String,AggregateResult> quoteHRCostMap = getQuoteHRCosts(quoteID);
        Map<String,AggregateResult> quoteCostMap = getQuoteCosts(quoteID);
        Map<String,AggregateResult> quoteRevenueMap = getQuoteRevenues(quoteID);
    
        Set<String> revenueTypeKeySet = new Set<String>();
        revenueTypeKeySet.addAll(quoteHRCostMap.keySet());
        revenueTypeKeySet.addAll(quoteCostMap.keySet());
        revenueTypeKeySet.addAll(quoteRevenueMap.keySet());

        for (String rT: revenueTypeKeySet){
            EconomicPlan econPlan= new EconomicPlan(); 
            econPlan.revenueType = rT;
           
            if(quoteRevenueMap.containsKey(rT)){
                econPlan.linksRevenue = getRevenue(quoteRevenueMap.get(rT)) !=null ? getRevenue(quoteRevenueMap.get(rT)) : 0;
                econPlan.ATI = getRevenueATI(quoteRevenueMap.get(rT)) !=null ? getRevenueATI(quoteRevenueMap.get(rT)) : 0;
            }else{
                econPlan.linksRevenue = 0;
                econPlan.ATI = 0;
            }
            if(quoteHRCostMap.containsKey(rT)){
                econPlan.costHR = getHRCost(quoteHRCostMap.get(rT)) !=null ? getHRCost(quoteHRCostMap.get(rT)) : 0;
            }else{
                econPlan.costHR = 0;
            }
            if(quoteCostMap.containsKey(rT)){
                econPlan.cost = getCost(quoteCostMap.get(rT)) !=null ? getCost(quoteCostMap.get(rT)) : 0;
            }else{
                econPlan.cost = 0;
            }
            econPlan.setMarginProfit();
            econPlan.setTotalRevenue();
            econplan.rowError = false;
            try {
                //Get DefaultMarginPercent, MinMarginPercent values for the current Revenue Type (rT), from RevenueTypesCS__c Custom Setting.
                RevenueTypesCS__c rTCustomSetting = RevenueTypesCS__c.getInstance(rT);
                econplan.defaultMarginPercent = rTCustomSetting.DefaultMargin__c /100;
                econplan.setMarginCheck();
                econplan.minMarginPercent = rTCustomSetting.MinMargin__c /100;
                econplan.setMinMargin();
            } catch (NullPointerException e) {
                //If Revenue type is not found then:
                econplan.defaultMarginPercent = null;
                econplan.marginCheck = false;
                econplan.rowError = true;   
                if(rT==null){
                    econPlan.revenueType = 'Revenue Type field not populated in one or many records.';
                } else{
                    econPlan.revenueType = 'Revenue Type missing or not found into Custom Setting: "Revenue Types CS" --> ('+econPlan.revenueType+')';
                }
            } 
            econPlanList.add(econPlan);
        }
        System.debug(' } Œ EconomicPlanController.getEconomicPlan');
        return  econPlanList;
    }

    /*
    * @description : Get Economic Plan rollUp fields from Quote.
    * @author Œ | 01-04-2021 
    * @param id quoteID 
    * @return EconomicPlan 
    **/
    @AuraEnabled(cacheable=true)
    public static EconomicPlan getTotalEconomicPlan(id quoteId){
        System.debug('Œ EconomicPlanController.getTotalEconomicPlan{ ');
        Double totalHRCost = 0;  
        Double totalCost = 0;
        Double totalLinksRevenue = 0;
        Double totalATI = 0;
        Double totalMinMargin = 0;
        for (EconomicPlan econP: getEconomicPlan(quoteId)){
            totalHRCost += econP.costHR;
            totalCost += econP.cost;
            totalLinksRevenue += econP.linksRevenue;
            totalATI += econP.ATI;
            totalMinMargin += econP.minMargin;
        }
        EconomicPlan econPlan= new EconomicPlan();
        econPlan.revenueType = 'TOTAL';
        econPlan.costHR = totalHRCost;
        econPlan.cost = totalCost;
        econPlan.linksRevenue = totalLinksRevenue;
        econPlan.ATI = totalATI;
        if(totalLinksRevenue!= 0){
            econPlan.minMarginPercent = totalMinMargin / totalLinksRevenue;
        }else{
            econPlan.minMarginPercent = 0;
        }
        econPlan.setTotalRevenue();
        econPlan.setMarginProfit(); 
        econPlan.setMinMargin();
        System.debug(' }Œ EconomicPlanController.getTotalEconomicPlan');
        return econPlan;
    }



    /**
    * @description : Set Quote's isMarginValid__c fields, according to the marginCheck got from the Javascript callback.
    * @author Œ | 09-04-2021 
    * @param CustomWrapper wrapper 
    * @return String
    **/
    @AuraEnabled
    public static Quote setQuoteIsMarginValid(CustomWrapper wrapper){
        System.debug('Œ EconomicPlanController.setQuoteIsMarginValid { ');
        
        Quote quote = [SELECT isMarginValid__c, isMinMarginValid__c, CostHRMargin__c, CostMargin__c, Status FROM Quote WHERE Id=:wrapper.quoteId LIMIT 1];
       
        if(wrapper.marginCheck != null  && wrapper.totalMarginCheck != null){
                    
                    quote.isMarginValid__c = wrapper.marginCheck;
                    quote.isMinMarginValid__c = wrapper.totalMarginCheck;
                    quote.CostHRMargin__c = wrapper.CostHRMargin;
                    quote.CostMargin__c = wrapper.CostMargin;
                    System.debug('Œ Update quoteToUpdate -> '+ quote);
                    try {
                        update quote;
                    } catch (Exception e) {
                        throw new AuraHandledException(e.getMessage());
                    } 
                    return quote;             
        }
        System.debug(' } Œ EconomicPlanController.setQuoteIsMarginValid ');
        return quote;
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param id quoteID 
    * @return Map<String, AggregateResult> 
    **/
    private static Map<String,AggregateResult> getQuoteHRCosts(id quoteID){
        List<AggregateResult> quoteHRCostsList = [SELECT SUM(TotalCost__c) TotalHRCost, toLabel(Revenue_Type__c) Revenue_Type__c
                                                    FROM QuoteLineItem 
                                                    WHERE quoteID=:quoteID 
                                                    GROUP BY Revenue_Type__c ];
        Map<String,AggregateResult> quoteHRCostsMap = new  Map<String,AggregateResult>();
        for (AggregateResult record: quoteHRCostsList){
            quoteHRCostsMap.put((String)record.get('Revenue_Type__c'), record);
        }
        return quoteHRCostsMap;

    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param id quoteID 
    * @return Map<String, AggregateResult> 
    **/
    private static Map<String,AggregateResult> getQuoteCosts(id quoteID){    
        List<AggregateResult> quoteCostsList = [SELECT SUM(TotalCostValue__c) TotalCost, toLabel(Revenue_Type__c) Revenue_Type__c
                                                    FROM Cost__c 
                                                    WHERE Quote__c=:quoteID 
                                                    GROUP BY Revenue_Type__c ];
        Map<String,AggregateResult> quoteCostsMap = new  Map<String,AggregateResult>();
        for (AggregateResult record: quoteCostsList){
            quoteCostsMap.put((String)record.get('Revenue_Type__c'), record);
        }
        return quoteCostsMap;
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param id quoteID 
    * @return Map<String, AggregateResult> 
    **/
    private static Map<String,AggregateResult> getQuoteRevenues(id quoteID){
        List<AggregateResult> quoteRevenueList = [SELECT SUM(LinksRevenue__c) TotalLinksRevenue, SUM(QuotaATI__c) TotalATI, toLabel(Revenue_Type__c) Revenue_Type__c
                                                    FROM Quote_Revenue__c 
                                                    WHERE Quote__c=:quoteID 
                                                    GROUP BY Revenue_Type__c ];
        Map<String,AggregateResult> quoteRevenueMap = new  Map<String,AggregateResult>();
        for (AggregateResult record: quoteRevenueList){
            quoteRevenueMap.put((String)record.get('Revenue_Type__c'), record);
        }
        return quoteRevenueMap;
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param AggregateResult HRCostList 
    * @return Double 
    **/
    private static Double getHRCost(AggregateResult HRCostList){
        return (Double)HRCostList.get('TotalHRCost');
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param AggregateResult costList 
    * @return Double 
    **/
    private static Double getCost(AggregateResult costList){
        return (Double)costList.get('TotalCost');
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param AggregateResult revenueList 
    * @return Double 
    **/
    private static Double getRevenue(AggregateResult revenueList){
        return (Double) revenueList.get('TotalLinksRevenue');
    }

    /**
    * @description 
    * @author Œ | 01-04-2021 
    * @param AggregateResult revenueATIList 
    * @return Double 
    **/
    private static Double getRevenueATI(AggregateResult revenueATIList){
        return (Double)revenueATIList.get('TotalATI');
    }

}