force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/InvoiceExternalCode__c.field-meta.xml
<CustomField>
    <fullName>InvoiceExternalCode__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter the invoice code present on the company billing system</inlineHelpText>
    <label>Invoice External Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/StartSendEmailWorkflow__c.field-meta.xml
<CustomField>
    <fullName>StartSendEmailWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SendEmail Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/recordTypes/NexusOneShot.recordType-meta.xml
<RecordType>
    <fullName>NexusOneShot</fullName>
    <active>true</active>
    <label>Nexus One Shot</label>
</RecordType>

force-app/main/default/objects/InvoiceMilestoneSetting__c/InvoiceMilestoneSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Invoice Milestone Setting</label>
</CustomObject>

force-app/main/default/objects/InvoiceMilestoneSetting__c/fields/IsCurrentRecordUsed__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentRecordUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Record Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneSetting__c/fields/StatoValueForSendEmail__c.field-meta.xml
<CustomField>
    <fullName>StatoValueForSendEmail__c</fullName>
    <label>Stato Value For Send Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_InvoiceMilestoneHandler.cls
@isTest
public class Test_InvoiceMilestoneHandler {

	@testSetup
	static void InvoiceDataSetup() {
		Account testAccount = new Account( Name = 'NexusAT' );
		Insert testAccount;
		
		Opportunity testOpportunity = new Opportunity (
			Name = 'testOpportunity',
			AccountId = testAccount.Id,
			StageName = 'Prospecting',
			CloseDate = Date.today(),
			Description = 'testOpportunityDescription'
			);
		Insert testOpportunity;

		InvoiceMilestoneSetting__c customSetting = new InvoiceMilestoneSetting__c(
			StatoValueForSendEmail__c = 'Da Fatturare',
			IsCurrentRecordUsed__c = true
			);
		Insert customSetting;

		InvoiceMilestone__c testInvoiceMilestone = new InvoiceMilestone__c (
			Amount__c = 100,
			InvoiceExternalCode__c = 'CODXFATTEXT231TEST1',
			Opportunity__c = testOpportunity.Id,
			Stage__c = 'Da Fatturare',
			StartSendEmailWorkflow__c = false,
			ExpectedDate__c  =  Date.valueOf('2019-06-28'),
			RecordTypeId = [SELECT Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'InvoiceMilestone__c' AND DeveloperName = 'NexusOneShot'].Id
			);
		Insert testInvoiceMilestone;
	}
	@isTest
	public static void startTestSendEmailWorkflow(){
		InvoiceMilestone__c testInvoiceMilestone = [SELECT Id FROM InvoiceMilestone__c WHERE InvoiceExternalCode__c = 'CODXFATTEXT231TEST1'];
		Test.StartTest();
		InvoiceMilestoneHandler.startSendEmailWorkflow(testInvoiceMilestone.Id);
		Test.StopTest();
	}
}