force-app/main/default/objects/InvoiceMilestone__c/InvoiceMilestone__c.object-meta.xml
<CustomObject>
    <label>Invoice Milestone</label>
    <nameField>
        <label>Invoice Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceMilestone__c/fields/ExpectedDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedDate__c</fullName>
    <label>Expected Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Da Fatturare</fullName>
            </value>
            <value>
                <fullName>Fattura Inviata</fullName>
            </value>
            <value>
                <fullName>Fattura Pagata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceMilestone__c/fields/StartSendEmailWorkflow__c.field-meta.xml
<CustomField>
    <fullName>StartSendEmailWorkflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SendEmail Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneSetting__c/InvoiceMilestoneSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Invoice Milestone Setting</label>
</CustomObject>

force-app/main/default/objects/InvoiceMilestoneSetting__c/fields/IsCurrentRecordUsed__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentRecordUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Record Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceMilestoneSetting__c/fields/StatoValueForSendEmail__c.field-meta.xml
<CustomField>
    <fullName>StatoValueForSendEmail__c</fullName>
    <label>Stato Value For Send Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceMilestoneHandler.cls
public class InvoiceMilestoneHandler {
	@AuraEnabled
	public static Boolean startSendEmailWorkflow(String InvoiceMilestoneId){
		Boolean success;
		InvoiceMilestoneSetting__c customSetting = [SELECT Id, StatoValueForSendEmail__c, IsCurrentRecordUsed__c
														  FROM InvoiceMilestoneSetting__c
														  WHERE IsCurrentRecordUsed__c = true LIMIT 1];
		System.debug(customSetting);
		List<InvoiceMilestone__c> invoiceListToUpdate = new  List<InvoiceMilestone__c>();
	
		List<InvoiceMilestone__c> InvoiceMilestoneList = [SELECT Id, Name, Opportunity__c,StartSendEmailWorkflow__c, ExpectedDate__c, Stage__c
														   FROM InvoiceMilestone__c
														   WHERE Id =: InvoiceMilestoneId];
		if(InvoiceMilestoneList.size() > 0) {
			for(InvoiceMilestone__c currentInvoice : InvoiceMilestoneList) {
				System.debug(currentInvoice);
				if(currentInvoice.Stage__c == customSetting.StatoValueForSendEmail__c) {
					currentInvoice.StartSendEmailWorkflow__c = true;
					invoiceListToUpdate.add(currentInvoice);
				}
			}
			try{
				Update invoiceListToUpdate;
				success = true;
				System.debug('update con successo');
			}catch (Exception ex) {
				success = false;
				System.debug('sono scoppiato');
				System.debug(ex.getMessage());
				System.debug(ex.getStackTraceString());
			}
		}
		return success;
	}
	}